---
title: "MGMT 30500: Business Statistics"
subtitle: "Mitch. Daniels School of Business, Purdue University"
---

<!--- # IMPORTANT REFERENCE: https://www.youtube.com/watch?v=uimdXPZc40I&list=PLkrJrLs7xfbXcEKhTCKRSr2VXH4yiBeXo&index=4 --->

<br>

<center>

*IMPORTANT*

*This document does not replace the official information in the course brightspace page*

</center>

<br>

### Course Description and Objectives

This course is designed to introduce students to basic data analysis techniques. Coverage includes the application of probability distributions (normal, $t$, binomial), sampling distributions, basic statistical inference methods, analysis of variance, applied linear regression techniques, logistic regression, time series analysis, statistical quality control, and decision analysis.

Our main goal is to instill the basic quantitative and data analysis skills needed by managers in modern business, where Business Analytics and Data Science have become essential. These skills will aid in data-driven decision-making, risk assessments, and policy formulation, and will enable managers to collaborate effectively with data analysis teams to enhance business performance.

Since modern data analysis is primarily performed using computers and various sophisticated software, this course will also emphasize software applications (such as Minitab, R, or Python). However, Microsoft Excel is the primary software tool demonstrated in this course.

**Course Website**: [https://davi-moreira.github.io/2025S_business_statistics_purdue_MGMT305/](https://davi-moreira.github.io/2025S_business_statistics_purdue_MGMT305/){target="_blank"}

### Instructor: [Professor Davi Moreira](https://davi-moreira.github.io)

-   Email: [dmoreira\@purdue.edu](mailto:dmoreira@purdue.edu)
-   Virtual Office hours: *Zoom link in your Course Brightspace Page*
-   Individual Appointments: *Book time with me through the link in the course syllabus on your Course Brightspace Page or by appointment.*

### Learning Outcomes

By the end of this course, students will be able to:

1.  Understand the basic statistical principles and their applications in the area of management and business.\
2.  Understand fundamental issues in business and management.\
3.  Describe and use the commonly used statistical techniques for analyzing business data.\
4.  Understand the impacts of recent developments in big data and AI in business and management.\
5.  Be proficient in using Excel to carry out statistical and analytics methods covered in the course.

### Prerequisite

-   **STAT 30301**: Probability and Statistics for Business.

### Course Materials

-   **Textbook**:\
    Anderson, Sweeney, Williams, Camn, Cochran, Fry, and Ohlmann.\
    *Modern Business Statistics with Microsoft Excel*, 7th Edition, 2020, Cengage Learning, Inc.\
    (Required; also used in STAT 30301)

-   **Handouts**:\
    Lecture Slides and Supplementary Materials (available on Brightspace).\
    The E-Book and handouts are located in Brightspace → Content → Table of Contents → …

-   **Computing**:\
    Quizzes will be administered in-person, and you will need to work on practice exercises in class. You should have access to a PC, Mac, or tablet.

-   **Software**:\
    Microsoft Excel is used for in-class demonstrations. Ensure the “Data Analysis” ToolPak is enabled:

    1.  `File -> Options -> Add-ins`\
    2.  Select **Analysis ToolPak** and **Analysis ToolPak-VBA** → `Go`\
    3.  **Data** → **Data Analysis** (for Excel-based analyses)

### Course Infra-structure

**Brightspace:** The Course Brightspace Page <https://purdue.brightspace.com/> should be checked on a regular basis for announcements and course material.

**Software:** Microsoft Excel will be used for in-class demonstrations and instruction. The main tool is Data Analysis under Tools. If you don’t see this tool, follow the following steps to add in:

-   File -\> Options -\> Add-ins -\> Select Analysis ToolPak and Analysis ToolPak-VBA (also select StatTools 7.5, if available) -\> Go -\> Data -\> Data Analysis (to conduct analyses)

**Course Website:** This class website will be used throughout the course, but it does not replace the Course Brightspace Page.
