<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Professor Davi Moreira ">

<title> MGMT 30500: Business Statistics  – MGMT 30500: Business Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-79df7ed5347781c1339259261daa236f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><span style="font-size: 100%;"> MGMT 30500: Business Statistics </span></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/mgmt_305_ai_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/davi-moreira/2025S_business_statistics_purdue_MGMT305" title="GitHub" class="quarto-navigation-tool px-1" aria-label="GitHub"><i class="bi bi-github"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../material.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Material</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#association-between-two-variables" id="toc-association-between-two-variables" class="nav-link" data-scroll-target="#association-between-two-variables">Association Between Two Variables</a>
  <ul class="collapse">
  <li><a href="#covariance" id="toc-covariance" class="nav-link" data-scroll-target="#covariance">Covariance</a></li>
  <li><a href="#correlation-coefficient" id="toc-correlation-coefficient" class="nav-link" data-scroll-target="#correlation-coefficient">Correlation Coefficient</a></li>
  </ul></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">Model</a>
  <ul class="collapse">
  <li><a href="#what-is-a-model" id="toc-what-is-a-model" class="nav-link" data-scroll-target="#what-is-a-model">What is a model?</a></li>
  <li><a href="#what-does-it-mean-to-model-data" id="toc-what-does-it-mean-to-model-data" class="nav-link" data-scroll-target="#what-does-it-mean-to-model-data">What does it mean to “model” data?</a></li>
  <li><a href="#what-does-it-mean-to-model-data-1" id="toc-what-does-it-mean-to-model-data-1" class="nav-link" data-scroll-target="#what-does-it-mean-to-model-data-1">What does it mean to “model” data?</a></li>
  </ul></li>
  <li><a href="#motivation-walmart-carton-mix-optimization-study" id="toc-motivation-walmart-carton-mix-optimization-study" class="nav-link" data-scroll-target="#motivation-walmart-carton-mix-optimization-study">Motivation: Walmart Carton-Mix Optimization Study</a>
  <ul class="collapse">
  <li><a href="#motivation-walmart-carton-mix-optimization-study-1" id="toc-motivation-walmart-carton-mix-optimization-study-1" class="nav-link" data-scroll-target="#motivation-walmart-carton-mix-optimization-study-1">Motivation: Walmart Carton-Mix Optimization Study</a></li>
  <li><a href="#motivation-walmart-carton-mix-optimization-study-2" id="toc-motivation-walmart-carton-mix-optimization-study-2" class="nav-link" data-scroll-target="#motivation-walmart-carton-mix-optimization-study-2">Motivation: Walmart Carton-Mix Optimization Study</a></li>
  <li><a href="#motivation-walmart-carton-mix-optimization-study-3" id="toc-motivation-walmart-carton-mix-optimization-study-3" class="nav-link" data-scroll-target="#motivation-walmart-carton-mix-optimization-study-3">Motivation: Walmart Carton-Mix Optimization Study</a></li>
  <li><a href="#motivation-walmart-carton-mix-optimization-study-4" id="toc-motivation-walmart-carton-mix-optimization-study-4" class="nav-link" data-scroll-target="#motivation-walmart-carton-mix-optimization-study-4">Motivation: Walmart Carton-Mix Optimization Study</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a></li>
  <li><a href="#simple-linear-regression-1" id="toc-simple-linear-regression-1" class="nav-link" data-scroll-target="#simple-linear-regression-1">Simple Linear Regression</a></li>
  <li><a href="#regression-objective" id="toc-regression-objective" class="nav-link" data-scroll-target="#regression-objective">Regression Objective</a></li>
  <li><a href="#applications" id="toc-applications" class="nav-link" data-scroll-target="#applications">Applications</a></li>
  <li><a href="#simple-linear-regression-model" id="toc-simple-linear-regression-model" class="nav-link" data-scroll-target="#simple-linear-regression-model">Simple Linear Regression Model</a></li>
  <li><a href="#simple-linear-regression-2" id="toc-simple-linear-regression-2" class="nav-link" data-scroll-target="#simple-linear-regression-2">Simple Linear Regression</a></li>
  <li><a href="#simple-linear-regression-equation" id="toc-simple-linear-regression-equation" class="nav-link" data-scroll-target="#simple-linear-regression-equation">Simple Linear Regression Equation</a></li>
  <li><a href="#simple-linear-regression-equation-1" id="toc-simple-linear-regression-equation-1" class="nav-link" data-scroll-target="#simple-linear-regression-equation-1">Simple Linear Regression Equation</a></li>
  <li><a href="#estimated-simple-linear-regression-equation" id="toc-estimated-simple-linear-regression-equation" class="nav-link" data-scroll-target="#estimated-simple-linear-regression-equation">Estimated Simple Linear Regression Equation</a></li>
  <li><a href="#random-error-epsilon-and-observed-residual-e" id="toc-random-error-epsilon-and-observed-residual-e" class="nav-link" data-scroll-target="#random-error-epsilon-and-observed-residual-e">Random Error (<span class="math inline">\(\epsilon\)</span>) and Observed Residual (<span class="math inline">\(e\)</span>)</a></li>
  <li><a href="#estimation-process" id="toc-estimation-process" class="nav-link" data-scroll-target="#estimation-process">Estimation Process</a></li>
  <li><a href="#residualserrors" id="toc-residualserrors" class="nav-link" data-scroll-target="#residualserrors">Residuals/Errors</a></li>
  </ul></li>
  <li><a href="#least-squares-method" id="toc-least-squares-method" class="nav-link" data-scroll-target="#least-squares-method">Least Squares Method</a>
  <ul class="collapse">
  <li><a href="#least-squares-method-1" id="toc-least-squares-method-1" class="nav-link" data-scroll-target="#least-squares-method-1">Least Squares Method</a></li>
  <li><a href="#least-squares-method-2" id="toc-least-squares-method-2" class="nav-link" data-scroll-target="#least-squares-method-2">Least Squares Method</a></li>
  <li><a href="#least-squares-method-3" id="toc-least-squares-method-3" class="nav-link" data-scroll-target="#least-squares-method-3">Least Squares Method</a></li>
  <li><a href="#regression-modeling-steps" id="toc-regression-modeling-steps" class="nav-link" data-scroll-target="#regression-modeling-steps">Regression Modeling Steps</a></li>
  <li><a href="#linear-regression-example" id="toc-linear-regression-example" class="nav-link" data-scroll-target="#linear-regression-example">Linear Regression: Example</a></li>
  <li><a href="#linear-regression-example-1" id="toc-linear-regression-example-1" class="nav-link" data-scroll-target="#linear-regression-example-1">Linear Regression: Example</a></li>
  <li><a href="#linear-regression-example-excel" id="toc-linear-regression-example-excel" class="nav-link" data-scroll-target="#linear-regression-example-excel">Linear Regression: Example Excel</a></li>
  <li><a href="#linear-regression-example-2" id="toc-linear-regression-example-2" class="nav-link" data-scroll-target="#linear-regression-example-2">Linear Regression: Example</a></li>
  <li><a href="#linear-regression-example-3" id="toc-linear-regression-example-3" class="nav-link" data-scroll-target="#linear-regression-example-3">Linear Regression: Example</a></li>
  <li><a href="#linear-regression-example-excel-1" id="toc-linear-regression-example-excel-1" class="nav-link" data-scroll-target="#linear-regression-example-excel-1">Linear Regression: Example Excel</a></li>
  <li><a href="#linear-regression-example-4" id="toc-linear-regression-example-4" class="nav-link" data-scroll-target="#linear-regression-example-4">Linear Regression: Example</a></li>
  <li><a href="#linear-regression-example-5" id="toc-linear-regression-example-5" class="nav-link" data-scroll-target="#linear-regression-example-5">Linear Regression: Example</a></li>
  <li><a href="#remarks" id="toc-remarks" class="nav-link" data-scroll-target="#remarks">Remarks</a></li>
  <li><a href="#partition-of-total-variation" id="toc-partition-of-total-variation" class="nav-link" data-scroll-target="#partition-of-total-variation">Partition of Total Variation</a></li>
  <li><a href="#partition-of-total-variation-1" id="toc-partition-of-total-variation-1" class="nav-link" data-scroll-target="#partition-of-total-variation-1">Partition of Total Variation</a></li>
  <li><a href="#partition-of-total-variation-2" id="toc-partition-of-total-variation-2" class="nav-link" data-scroll-target="#partition-of-total-variation-2">Partition of Total Variation</a></li>
  <li><a href="#derivation-of-the-total-sum-of-squares-sst" id="toc-derivation-of-the-total-sum-of-squares-sst" class="nav-link" data-scroll-target="#derivation-of-the-total-sum-of-squares-sst">Derivation of the Total Sum of Squares (SST)</a></li>
  </ul></li>
  <li><a href="#coefficient-of-determination" id="toc-coefficient-of-determination" class="nav-link" data-scroll-target="#coefficient-of-determination">Coefficient of Determination</a>
  <ul class="collapse">
  <li><a href="#coefficient-of-determination-1" id="toc-coefficient-of-determination-1" class="nav-link" data-scroll-target="#coefficient-of-determination-1">Coefficient of Determination</a></li>
  <li><a href="#coefficient-of-determination-2" id="toc-coefficient-of-determination-2" class="nav-link" data-scroll-target="#coefficient-of-determination-2">Coefficient of Determination</a></li>
  <li><a href="#coefficient-of-determination-3" id="toc-coefficient-of-determination-3" class="nav-link" data-scroll-target="#coefficient-of-determination-3">Coefficient of Determination</a></li>
  <li><a href="#coefficient-of-determination-excel" id="toc-coefficient-of-determination-excel" class="nav-link" data-scroll-target="#coefficient-of-determination-excel">Coefficient of Determination: Excel</a></li>
  <li><a href="#sample-correlation-coefficient" id="toc-sample-correlation-coefficient" class="nav-link" data-scroll-target="#sample-correlation-coefficient">Sample Correlation Coefficient</a></li>
  <li><a href="#sample-correlation-coefficient-1" id="toc-sample-correlation-coefficient-1" class="nav-link" data-scroll-target="#sample-correlation-coefficient-1">Sample Correlation Coefficient</a></li>
  </ul></li>
  <li><a href="#model-assumptions" id="toc-model-assumptions" class="nav-link" data-scroll-target="#model-assumptions">Model Assumptions</a>
  <ul class="collapse">
  <li><a href="#assumptions-about-the-error-term-epsilon" id="toc-assumptions-about-the-error-term-epsilon" class="nav-link" data-scroll-target="#assumptions-about-the-error-term-epsilon">Assumptions About the Error Term <span class="math inline">\(\epsilon\)</span></a></li>
  <li><a href="#assumptions-about-the-error-term-epsilon-1" id="toc-assumptions-about-the-error-term-epsilon-1" class="nav-link" data-scroll-target="#assumptions-about-the-error-term-epsilon-1">Assumptions About the Error Term <span class="math inline">\(\epsilon\)</span></a></li>
  </ul></li>
  <li><a href="#testing-for-significance" id="toc-testing-for-significance" class="nav-link" data-scroll-target="#testing-for-significance">Testing for Significance</a>
  <ul class="collapse">
  <li><a href="#testing-for-significance-1" id="toc-testing-for-significance-1" class="nav-link" data-scroll-target="#testing-for-significance-1">Testing for Significance</a></li>
  <li><a href="#testing-for-significance-2" id="toc-testing-for-significance-2" class="nav-link" data-scroll-target="#testing-for-significance-2">Testing for Significance</a></li>
  <li><a href="#testing-for-significance-3" id="toc-testing-for-significance-3" class="nav-link" data-scroll-target="#testing-for-significance-3">Testing for Significance</a></li>
  <li><a href="#testing-for-overall-significance-f-test" id="toc-testing-for-overall-significance-f-test" class="nav-link" data-scroll-target="#testing-for-overall-significance-f-test">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</a></li>
  <li><a href="#testing-for-overall-significance-f-test-1" id="toc-testing-for-overall-significance-f-test-1" class="nav-link" data-scroll-target="#testing-for-overall-significance-f-test-1">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</a></li>
  <li><a href="#testing-for-overall-significance-f-test-2" id="toc-testing-for-overall-significance-f-test-2" class="nav-link" data-scroll-target="#testing-for-overall-significance-f-test-2">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</a></li>
  <li><a href="#testing-for-individual-significance-t-test" id="toc-testing-for-individual-significance-t-test" class="nav-link" data-scroll-target="#testing-for-individual-significance-t-test">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</a></li>
  <li><a href="#testing-for-individual-significance-t-test-1" id="toc-testing-for-individual-significance-t-test-1" class="nav-link" data-scroll-target="#testing-for-individual-significance-t-test-1">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</a></li>
  <li><a href="#testing-for-individual-significance-t-test-2" id="toc-testing-for-individual-significance-t-test-2" class="nav-link" data-scroll-target="#testing-for-individual-significance-t-test-2">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</a></li>
  <li><a href="#confidence-interval-for-beta_1" id="toc-confidence-interval-for-beta_1" class="nav-link" data-scroll-target="#confidence-interval-for-beta_1">Confidence Interval for <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#confidence-interval-for-beta_1-1" id="toc-confidence-interval-for-beta_1-1" class="nav-link" data-scroll-target="#confidence-interval-for-beta_1-1">Confidence Interval for <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#confidence-interval-for-beta_1-2" id="toc-confidence-interval-for-beta_1-2" class="nav-link" data-scroll-target="#confidence-interval-for-beta_1-2">Confidence Interval for <span class="math inline">\(\beta_1\)</span></a></li>
  <li><a href="#some-cautions-about-the-interpretation-of-significance-tests" id="toc-some-cautions-about-the-interpretation-of-significance-tests" class="nav-link" data-scroll-target="#some-cautions-about-the-interpretation-of-significance-tests">Some Cautions about the Interpretation of Significance Tests</a></li>
  </ul></li>
  <li><a href="#excels-regression-tool" id="toc-excels-regression-tool" class="nav-link" data-scroll-target="#excels-regression-tool">Excel’s Regression Tool</a>
  <ul class="collapse">
  <li><a href="#excels-regression-tool-1" id="toc-excels-regression-tool-1" class="nav-link" data-scroll-target="#excels-regression-tool-1">Excel’s Regression Tool</a></li>
  <li><a href="#using-excels-regression-tool" id="toc-using-excels-regression-tool" class="nav-link" data-scroll-target="#using-excels-regression-tool">Using Excel’s Regression Tool</a></li>
  <li><a href="#using-excels-regression-tool-1" id="toc-using-excels-regression-tool-1" class="nav-link" data-scroll-target="#using-excels-regression-tool-1">Using Excel’s Regression Tool</a></li>
  <li><a href="#using-excels-regression-tool-2" id="toc-using-excels-regression-tool-2" class="nav-link" data-scroll-target="#using-excels-regression-tool-2">Using Excel’s Regression Tool</a></li>
  <li><a href="#using-excels-regression-tool-3" id="toc-using-excels-regression-tool-3" class="nav-link" data-scroll-target="#using-excels-regression-tool-3">Using Excel’s Regression Tool</a></li>
  </ul></li>
  <li><a href="#using-the-estimated-regression-equation-for-estimation-and-prediction" id="toc-using-the-estimated-regression-equation-for-estimation-and-prediction" class="nav-link" data-scroll-target="#using-the-estimated-regression-equation-for-estimation-and-prediction">Using the Estimated Regression Equation for Estimation and Prediction</a>
  <ul class="collapse">
  <li><a href="#using-the-estimated-regression-equation-for-estimation-and-prediction-1" id="toc-using-the-estimated-regression-equation-for-estimation-and-prediction-1" class="nav-link" data-scroll-target="#using-the-estimated-regression-equation-for-estimation-and-prediction-1">Using the Estimated Regression Equation for Estimation and Prediction</a></li>
  <li><a href="#using-the-estimated-regression-equation-for-estimation-and-prediction-2" id="toc-using-the-estimated-regression-equation-for-estimation-and-prediction-2" class="nav-link" data-scroll-target="#using-the-estimated-regression-equation-for-estimation-and-prediction-2">Using the Estimated Regression Equation for Estimation and Prediction</a></li>
  <li><a href="#point-estimation" id="toc-point-estimation" class="nav-link" data-scroll-target="#point-estimation">Point Estimation</a></li>
  <li><a href="#sums-of-squares" id="toc-sums-of-squares" class="nav-link" data-scroll-target="#sums-of-squares">Sums of Squares</a></li>
  <li><a href="#confidence-interval-for-ehaty" id="toc-confidence-interval-for-ehaty" class="nav-link" data-scroll-target="#confidence-interval-for-ehaty">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></a></li>
  <li><a href="#confidence-interval-for-ehaty-1" id="toc-confidence-interval-for-ehaty-1" class="nav-link" data-scroll-target="#confidence-interval-for-ehaty-1">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></a></li>
  <li><a href="#confidence-interval-for-ehaty-2" id="toc-confidence-interval-for-ehaty-2" class="nav-link" data-scroll-target="#confidence-interval-for-ehaty-2">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></a></li>
  <li><a href="#prediction-interval-for-y" id="toc-prediction-interval-for-y" class="nav-link" data-scroll-target="#prediction-interval-for-y">Prediction Interval for <span class="math inline">\(y^*\)</span></a></li>
  <li><a href="#prediction-interval-for-y-1" id="toc-prediction-interval-for-y-1" class="nav-link" data-scroll-target="#prediction-interval-for-y-1">Prediction Interval for <span class="math inline">\(y^*\)</span></a></li>
  <li><a href="#prediction-interval-for-y-2" id="toc-prediction-interval-for-y-2" class="nav-link" data-scroll-target="#prediction-interval-for-y-2">Prediction Interval for <span class="math inline">\(y^*\)</span></a></li>
  <li><a href="#comments" id="toc-comments" class="nav-link" data-scroll-target="#comments">Comments</a></li>
  </ul></li>
  <li><a href="#residual-analysis-validating-model-assumptions" id="toc-residual-analysis-validating-model-assumptions" class="nav-link" data-scroll-target="#residual-analysis-validating-model-assumptions">Residual Analysis: Validating Model Assumptions</a>
  <ul class="collapse">
  <li><a href="#residual-analysis-validating-model-assumptions-1" id="toc-residual-analysis-validating-model-assumptions-1" class="nav-link" data-scroll-target="#residual-analysis-validating-model-assumptions-1">Residual Analysis: Validating Model Assumptions</a></li>
  <li><a href="#model-assumptions-and-validation-procedures-with-diagnosis-plots" id="toc-model-assumptions-and-validation-procedures-with-diagnosis-plots" class="nav-link" data-scroll-target="#model-assumptions-and-validation-procedures-with-diagnosis-plots">Model Assumptions and Validation Procedures with Diagnosis Plots</a></li>
  <li><a href="#residual-plot-against-x" id="toc-residual-plot-against-x" class="nav-link" data-scroll-target="#residual-plot-against-x">Residual Plot Against <span class="math inline">\(x\)</span></a></li>
  <li><a href="#residual-plot-against-x-1" id="toc-residual-plot-against-x-1" class="nav-link" data-scroll-target="#residual-plot-against-x-1">Residual Plot Against <span class="math inline">\(x\)</span></a></li>
  <li><a href="#residual-plot-against-x-2" id="toc-residual-plot-against-x-2" class="nav-link" data-scroll-target="#residual-plot-against-x-2">Residual Plot Against <span class="math inline">\(x\)</span></a></li>
  <li><a href="#residual-plot-against-x---excel" id="toc-residual-plot-against-x---excel" class="nav-link" data-scroll-target="#residual-plot-against-x---excel">Residual Plot Against <span class="math inline">\(x\)</span> - Excel</a></li>
  <li><a href="#residual-plot-against-haty" id="toc-residual-plot-against-haty" class="nav-link" data-scroll-target="#residual-plot-against-haty">Residual Plot Against <span class="math inline">\(\hat{y}\)</span></a></li>
  <li><a href="#standardized-residuals" id="toc-standardized-residuals" class="nav-link" data-scroll-target="#standardized-residuals">Standardized Residuals</a></li>
  <li><a href="#standardized-residual-plot" id="toc-standardized-residual-plot" class="nav-link" data-scroll-target="#standardized-residual-plot">Standardized Residual Plot</a></li>
  <li><a href="#standardized-residual" id="toc-standardized-residual" class="nav-link" data-scroll-target="#standardized-residual">Standardized Residual</a></li>
  <li><a href="#standardized-residual-plot-1" id="toc-standardized-residual-plot-1" class="nav-link" data-scroll-target="#standardized-residual-plot-1">Standardized Residual Plot</a></li>
  <li><a href="#using-excel-to-construct-a-standardized-residual-plot" id="toc-using-excel-to-construct-a-standardized-residual-plot" class="nav-link" data-scroll-target="#using-excel-to-construct-a-standardized-residual-plot">Using Excel to construct a Standardized Residual Plot</a></li>
  <li><a href="#normal-probability-plot" id="toc-normal-probability-plot" class="nav-link" data-scroll-target="#normal-probability-plot">Normal Probability Plot</a></li>
  <li><a href="#normal-probability-plot-1" id="toc-normal-probability-plot-1" class="nav-link" data-scroll-target="#normal-probability-plot-1">Normal Probability Plot</a></li>
  <li><a href="#normal-probability-plot-2" id="toc-normal-probability-plot-2" class="nav-link" data-scroll-target="#normal-probability-plot-2">Normal Probability Plot</a></li>
  <li><a href="#normal-probability-plot-3" id="toc-normal-probability-plot-3" class="nav-link" data-scroll-target="#normal-probability-plot-3">Normal Probability Plot</a></li>
  </ul></li>
  <li><a href="#outliers-and-influential-observations" id="toc-outliers-and-influential-observations" class="nav-link" data-scroll-target="#outliers-and-influential-observations">Outliers and Influential Observations</a>
  <ul class="collapse">
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers">Outliers</a></li>
  <li><a href="#detecting-outliers" id="toc-detecting-outliers" class="nav-link" data-scroll-target="#detecting-outliers">Detecting Outliers</a></li>
  <li><a href="#detecting-outliers-with-standardized-residuals" id="toc-detecting-outliers-with-standardized-residuals" class="nav-link" data-scroll-target="#detecting-outliers-with-standardized-residuals">Detecting Outliers with Standardized Residuals</a></li>
  <li><a href="#detecting-outliers-1" id="toc-detecting-outliers-1" class="nav-link" data-scroll-target="#detecting-outliers-1">Detecting Outliers</a></li>
  <li><a href="#influential-observations" id="toc-influential-observations" class="nav-link" data-scroll-target="#influential-observations">Influential Observations</a></li>
  <li><a href="#detecting-influential-observations" id="toc-detecting-influential-observations" class="nav-link" data-scroll-target="#detecting-influential-observations">Detecting Influential Observations</a></li>
  <li><a href="#detecting-influential-observations-1" id="toc-detecting-influential-observations-1" class="nav-link" data-scroll-target="#detecting-influential-observations-1">Detecting Influential Observations</a></li>
  <li><a href="#detecting-influential-observations-2" id="toc-detecting-influential-observations-2" class="nav-link" data-scroll-target="#detecting-influential-observations-2">Detecting Influential Observations</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a>
  <ul class="collapse">
  <li><a href="#summary-1" id="toc-summary-1" class="nav-link" data-scroll-target="#summary-1">Summary</a></li>
  </ul></li>
  <li><a href="#thank-you" id="toc-thank-you" class="nav-link" data-scroll-target="#thank-you">Thank you!</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="14_chapter_simple_regression.html"><i class="bi bi-file-slides"></i>RevealJS</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span style="font-size: 100%;"> MGMT 30500: Business Statistics </span></h1>
<p class="subtitle lead"><span style="font-size: 150%;"> Simple Linear Regression</span></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Professor<br>Davi Moreira<br> </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<div class="nonincremental">
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Simple Linear Regression Model</li>
<li>Least Squares Method</li>
<li>Coefficient of Determination</li>
<li>Model Assumptions</li>
<li>Testing for Significance</li>
</ul>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<ul>
<li>Excel’s Regression Tool</li>
<li>Using the Estimated Regression Equation for Estimation and Prediction</li>
<li>Residual Analysis: Validating Model Assumptions</li>
<li>Outliers and Influential Observations</li>
</ul>
</div>
</div>
</div>
</section>
<section id="association-between-two-variables" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Association Between Two Variables</h1>
<section id="covariance" class="level2">
<h2 class="anchored" data-anchor-id="covariance">Covariance</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/scatter_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="nonincremental">
<ul>
<li>The <a href="https://en.wikipedia.org/wiki/Covariance">Covariance</a> is a measure of the linear association between two variables.</li>
<li>Positive values indicate a positive relationship.</li>
<li>Negative values indicate a negative relationship.</li>
</ul>
</div>
<p><br></p>
<p><br></p>
</section>
<section id="correlation-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="correlation-coefficient">Correlation Coefficient</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/xkcd.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="nonincremental">
<ul>
<li><p><a href="https://en.wikipedia.org/wiki/Correlation">Correlation</a> is a unit-free measure of linear association and not necessarily causation.</p></li>
<li><p>The coefficient can take on values between −1 and +1.</p>
<ul>
<li>Values near −1 indicate a strong negative linear relationship.</li>
<li>Values near +1 indicate a strong positive linear relationship.</li>
</ul></li>
<li><p>The closer the correlation is to zero, the weaker the linear relationship.</p></li>
</ul>
</div>
<p><br></p>
</section>
</section>
<section id="model" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Model</h1>
<section id="what-is-a-model" class="level2">
<h2 class="anchored" data-anchor-id="what-is-a-model">What is a model?</h2>
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<p><br></p>
<p><br></p>
<p><br></p>
<blockquote class="blockquote">
<p>All models are wrong, but some are useful.</p>
<p>— George Box</p>
</blockquote>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/metro.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<center>
<a href="https://new.mta.info/map/5256">NY City Subway Map</a>
</center>
</div>
</div>
<p><br></p>
</section>
<section id="what-does-it-mean-to-model-data" class="level2">
<h2 class="anchored" data-anchor-id="what-does-it-mean-to-model-data">What does it mean to “model” data?</h2>
<p><br></p>
<ul>
<li><p>Let’s start with a very simple premise:</p>
<ul>
<li>to model, we need to make explicit the conditions under which a variable <span class="math inline">\(X\)</span> is related to a variable <span class="math inline">\(Y\)</span>.</li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li><p>Let’s begin by giving specific names to these variables:</p>
<ul>
<li><p><strong>Dependent Variable (DV)</strong>: This is our phenomenon of interest, usually denoted as <span class="math inline">\(Y\)</span>.</p></li>
<li><p><strong>Independent Variable (IV)</strong>: This is the phenomenon that explains/describe our dependent variable, generally denoted as <span class="math inline">\(X\)</span>.</p></li>
</ul></li>
</ul>
</section>
<section id="what-does-it-mean-to-model-data-1" class="level2">
<h2 class="anchored" data-anchor-id="what-does-it-mean-to-model-data-1">What does it mean to “model” data?</h2>
<p><br></p>
<p>Mathematically, we model <span class="math inline">\(Y\)</span> as a <em>function</em> of <span class="math inline">\(X\)</span>. Statistically, modeling can serve two main purposes:</p>
<ol type="1">
<li><p><a href="https://www.statlearning.com/"><strong>Prediction</strong></a>: The possibility of using the values of <span class="math inline">\(X\)</span> to predict the value of <span class="math inline">\(Y\)</span>. There must be a substantive connection between these two variables for one to generate reliable predictions about the values of the other.</p></li>
<li><p><a href="https://moderndive.com/5-regression.html"><strong>Explanation</strong></a>: Used to understand the connection and significance (both substantive and statistical) of the relationship between two variables. In this case, we aim to accurately estimate the impact of one variable on the other, preferably excluding any potential omitted variables.</p></li>
</ol>
</section>
</section>
<section id="motivation-walmart-carton-mix-optimization-study" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Motivation: Walmart Carton-Mix Optimization Study</h1>
<section id="motivation-walmart-carton-mix-optimization-study-1" class="level2">
<h2 class="anchored" data-anchor-id="motivation-walmart-carton-mix-optimization-study-1">Motivation: Walmart Carton-Mix Optimization Study</h2>
<p><br></p>
<ul>
<li><p>Walmart is the world’s largest retailer with over 245 million customers weekly.</p></li>
<li><p>In 2000, Walmart launched its online shopping site, <code>Walmart.com</code>.</p></li>
<li><p>A network of distribution centers was created in the US to manage packaging for online orders.</p></li>
</ul>
</section>
<section id="motivation-walmart-carton-mix-optimization-study-2" class="level2">
<h2 class="anchored" data-anchor-id="motivation-walmart-carton-mix-optimization-study-2">Motivation: Walmart Carton-Mix Optimization Study</h2>
<p><br></p>
<p><strong>Carton-Mix Optimization Study</strong></p>
<ul>
<li><p><strong>Location</strong>: Carrollton, Georgia distribution center.</p></li>
<li><p><strong>Objective</strong>: Minimize material, labor, and shipping costs by optimizing the size and number of cartons.</p></li>
<li><p><strong>Constraints</strong>:</p>
<ul>
<li>Minimum and maximum carton sizes.</li>
<li>One-size carton limit for automatically constructed cartons.</li>
</ul></li>
<li><p><strong>Peak Season</strong>: November to December, with over 100,000 packages shipped per day.</p></li>
</ul>
</section>
<section id="motivation-walmart-carton-mix-optimization-study-3" class="level2">
<h2 class="anchored" data-anchor-id="motivation-walmart-carton-mix-optimization-study-3">Motivation: Walmart Carton-Mix Optimization Study</h2>
<div class="nonincremental">
<ul>
<li>Data was collected to develop a cost model for optimizing carton mix.</li>
<li>DV: material cost of a carton in dollars per carton.</li>
<li>IV: volume of the carton measured in cubic inches per carton.</li>
<li><strong>Cost Model Formula</strong>:</li>
</ul>
<p><span class="math display">\[
y = -0.11 + 0.0014x
\]</span></p>
<ul>
<li><p>Example Calculation:</p>
<ul>
<li>Carton volume: 2800 cubic inches</li>
<li>Estimated material cost: <span class="math inline">\(y = -0.11 + 0.0014 \times 2800 = 3.81\)</span></li>
</ul></li>
</ul>
</div>
</section>
<section id="motivation-walmart-carton-mix-optimization-study-4" class="level2">
<h2 class="anchored" data-anchor-id="motivation-walmart-carton-mix-optimization-study-4">Motivation: Walmart Carton-Mix Optimization Study</h2>
<div class="nonincremental">
<p><strong>Implementation and Results</strong></p>
<ul>
<li>The regression model was used in an optimization algorithm in Microsoft Excel to provide Walmart managers a recommendation on the optimal mix of carton sizes to carry at the distribution center.</li>
</ul>
<p><strong>Results</strong>:</p>
<ul>
<li><p>First-year savings: $600,000</p></li>
<li><p>Estimated annual savings across all distribution centers: $2 million</p></li>
</ul>
</div>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<p><br></p>
<ul>
<li><p>Managerial decisions often are based on the relationship between two or more variables.</p></li>
<li><p><strong>Regression analysis</strong> can be used to develop an equation (as a conjecture) for the relationship between the variables.</p>
<ul>
<li>The variable being predicted is called the <strong>dependent variable</strong> and is denoted by <strong>y</strong>.</li>
<li>The variables being used to predict the value of the dependent variable are called the <strong>independent variables</strong> and are denoted by <strong>x</strong>.</li>
</ul></li>
</ul>
</section>
<section id="simple-linear-regression-1" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-1">Simple Linear Regression</h2>
<p><br></p>
<ul>
<li><p><strong>Simple linear regression</strong> involves one independent variable and one dependent variable.</p></li>
<li><p>The relationship between the two variables is linear, approximated by a straight line.</p>
<ul>
<li>As an initial estimate of the unknown relationship.</li>
<li>A regression analysis is a trial-and-error exercise.</li>
</ul></li>
<li><p>Regression analysis involving two or more independent variables is called <strong>multiple regression</strong>.</p></li>
</ul>
</section>
<section id="regression-objective" class="level2">
<h2 class="anchored" data-anchor-id="regression-objective">Regression Objective</h2>
<p><br></p>
<ul>
<li><p><strong>Interpretation</strong>: Determine whether variation in the dependent variable can be explained by (the variation of) the independent variable(s) by testing the statistical significance of the independent variable(s):</p>
<ul>
<li>As a group (F-test).</li>
<li>Individually (t-tests).</li>
</ul></li>
<li><p><strong>Prediction</strong>: Study how to predict the dependent variable given the information of the independent variable(s).</p></li>
</ul>
<!--- Note: Data-driven regression contains only curve-fitting (i.e., obtaining the estimated line). Only calculus is involved.--->
</section>
<section id="applications" class="level2">
<h2 class="anchored" data-anchor-id="applications">Applications</h2>
<p><br></p>
<ul>
<li>Revenue vs.&nbsp;Advertising expenditure</li>
<li>Total cost vs.&nbsp;production quantity (variable and fixed costs)</li>
<li>NFL: Annual revenue vs.&nbsp;estimated team value</li>
<li>Total points earned vs.&nbsp;hours spent studying</li>
<li>Number of days absent vs.&nbsp;distance to work</li>
<li>Number of defective parts vs.&nbsp;line speed</li>
<li>Maintenance cost vs.&nbsp;age of the equipment</li>
<li>Sale price of 2007 Camry vs.&nbsp;mileage</li>
<li>Sales vs.&nbsp;promotion activities and Price</li>
<li>(Beta risk) Total return of an individual stock vs.&nbsp;total return for the stock market</li>
<li>Output vs.&nbsp;input</li>
</ul>
</section>
<section id="simple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-model">Simple Linear Regression Model</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><p>The equation that describes how <strong>y</strong> is related to <strong>x</strong> and an error term is called the <strong>regression model</strong>.</p></li>
<li><p>The <strong>simple linear regression model</strong> for the data is:</p></li>
</ul>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x + \epsilon
\]</span></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the unknown <strong>parameters</strong> of the model,</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> is a random variable called the <strong>error term</strong> (unexplained error), with mean of 0 and unknown <strong>error variance</strong> <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ul>
</div>
</section>
<section id="simple-linear-regression-2" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-2">Simple Linear Regression</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_error.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="simple-linear-regression-equation" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-equation">Simple Linear Regression Equation</h2>
<div class="nonincremental">
<p><br></p>
<ul>
<li>The <strong>Simple Linear Regression Equation</strong> is:</li>
</ul>
<p><span class="math display">\[
E(y) = \beta_0 + \beta_1 x
\]</span></p>
<p>Graph of the regression equation is a straight line.</p>
<ul>
<li><span class="math inline">\(E(y)\)</span> is the expected value of <strong>y</strong> for a given <strong>x</strong> value</li>
<li><span class="math inline">\(\beta_0\)</span> is the <strong>y</strong> intercept of the regression line (unknown)</li>
<li><span class="math inline">\(\beta_1\)</span> is the slope of the regression line (unknown)</li>
</ul>
</div>
</section>
<section id="simple-linear-regression-equation-1" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression-equation-1">Simple Linear Regression Equation</h2>
<div class="r-fit-text">
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="columns quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_relationship_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<center>
Positive Linear Relationship
</center>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_relationship_02.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<center>
Negative Linear Relationship
</center>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_relationship_03.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<center>
No Linear Relationship
</center>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="estimated-simple-linear-regression-equation" class="level2">
<h2 class="anchored" data-anchor-id="estimated-simple-linear-regression-equation">Estimated Simple Linear Regression Equation</h2>
<p><br></p>
<p>The <strong>estimated simple linear regression equation</strong>:</p>
<p><span class="math display">\[
\hat{y} = b_0 + b_1 x
\]</span></p>
<p>The graph is called the estimated/predicted regression line.</p>
<ul>
<li><span class="math inline">\(\hat{y}\)</span> is the estimated/predicted value of <strong>y</strong> for a given <strong>x</strong> value.</li>
<li><span class="math inline">\(b_0\)</span> is the <strong>y</strong>-intercept of the line, estimating <span class="math inline">\(\beta_0\)</span></li>
<li><span class="math inline">\(b_1\)</span> is the slope of the line, estimating <span class="math inline">\(\beta_1\)</span></li>
</ul>
</section>
<section id="random-error-epsilon-and-observed-residual-e" class="level2">
<h2 class="anchored" data-anchor-id="random-error-epsilon-and-observed-residual-e">Random Error (<span class="math inline">\(\epsilon\)</span>) and Observed Residual (<span class="math inline">\(e\)</span>)</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_error_02.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="estimation-process" class="level2">
<h2 class="anchored" data-anchor-id="estimation-process">Estimation Process</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_estimation.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="residualserrors" class="level2">
<h2 class="anchored" data-anchor-id="residualserrors">Residuals/Errors</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_residuals.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="least-squares-method" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Least Squares Method</h1>
<section id="least-squares-method-1" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-method-1">Least Squares Method</h2>
<p><br></p>
<div class="nonincremental">
<p><span class="math inline">\(y_i\)</span> = observed value of the dependent variable for the <strong>i</strong>-th observation.</p>
<p><span class="math inline">\(\hat{y}_i\)</span> = estimated value of the dependent variable for the <strong>i</strong>-th observation.</p>
<p><span class="math display">\[
\text{Error or Residual} = \text{Observed} - \text{Predicted} = y_i - \hat{y}_i
\]</span></p>
<ul>
<li><strong>Least Squares Criterion</strong>: To minimize the <strong>Sum of Squared Errors (SSE)</strong></li>
</ul>
<p><span class="math display">\[
\min SSE = \min \sum (y_i - \hat{y}_i)^2 = \min \sum (y_i - b_0 - b_1 x_i)^2
\]</span></p>
</div>
</section>
<section id="least-squares-method-2" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-method-2">Least Squares Method</h2>
<p><br></p>
<div class="nonincremental">
<p>Slope for the Estimated Regression Equation</p>
<p><span class="math display">\[
b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2}
\]</span></p>
</div>
<p>where:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> = value of independent variable for <strong>i</strong>-th observation</li>
<li><span class="math inline">\(y_i\)</span> = value of dependent variable for <strong>i</strong>-th observation</li>
<li><span class="math inline">\(\bar{x}\)</span> = mean value for independent variable</li>
<li><span class="math inline">\(\bar{y}\)</span> = mean value for dependent variable</li>
</ul>
</section>
<section id="least-squares-method-3" class="level2">
<h2 class="anchored" data-anchor-id="least-squares-method-3">Least Squares Method</h2>
<p><br></p>
<p><strong>y-Intercept for the Estimated Regression Equation</strong></p>
<p><span class="math display">\[
b_0 = \bar{y} - b_1 \bar{x}
\]</span></p>
</section>
<section id="regression-modeling-steps" class="level2">
<h2 class="anchored" data-anchor-id="regression-modeling-steps">Regression Modeling Steps</h2>
<p><br></p>
<div style="font-size: 80%;">
<ol type="1">
<li>Define problem and propose model</li>
<li>Make model assumptions</li>
<li>Collect data</li>
<li>Do descriptive data analysis</li>
<li>Obtain the prediction equation and evaluate the model
<ul>
<li>Estimate the regression coefficients</li>
<li>Check adequacy of the overall model</li>
<li>Test significance of the overall model and the individual independent variables</li>
<li>Residual Analysis: Validate the model assumptions</li>
</ul></li>
<li>Special issues (in multiple regression)
<ul>
<li>Multicollinearity and variables selection</li>
</ul></li>
<li>Special models and transformations (for model-building)</li>
<li>(Repeat Steps 1-7 if necessary.)</li>
<li>Prediction, Implementation, …</li>
</ol>
</div>
</section>
<section id="linear-regression-example" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example">Linear Regression: Example</h2>
<p><br></p>
<p><strong>Example</strong>: Armand’s Pizza Parlor Restaurants</p>
<p>Data was collected from a sample of 10 Armand’s Pizza Parlor Restaurants near college campuses.</p>
<p>For the <em>i-th</em> observation or restaurant in the sample:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> is the size of the student population</li>
<li><span class="math inline">\(y_i\)</span> is the quarterly sales.</li>
</ul>
</section>
<section id="linear-regression-example-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-1">Linear Regression: Example</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Restaurant</th>
<th>Student population (1000s)</th>
<th>Quarterly sales ($1000s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>58</td>
</tr>
<tr class="even">
<td>2</td>
<td>6</td>
<td>105</td>
</tr>
<tr class="odd">
<td>3</td>
<td>8</td>
<td>88</td>
</tr>
<tr class="even">
<td>4</td>
<td>8</td>
<td>118</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>117</td>
</tr>
<tr class="even">
<td>6</td>
<td>16</td>
<td>137</td>
</tr>
<tr class="odd">
<td>7</td>
<td>20</td>
<td>157</td>
</tr>
<tr class="even">
<td>8</td>
<td>20</td>
<td>169</td>
</tr>
<tr class="odd">
<td>9</td>
<td>22</td>
<td>149</td>
</tr>
<tr class="even">
<td>10</td>
<td>26</td>
<td>202</td>
</tr>
</tbody>
</table>
</section>
<section id="linear-regression-example-excel" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-excel">Linear Regression: Example Excel</h2>
<p><br></p>
<p><strong>Example</strong>: Armand’s Pizza Parlor Restaurants</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p><br></p>
</section>
<section id="linear-regression-example-2" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-2">Linear Regression: Example</h2>
<div style="font-size: 80%;">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Population</th>
<th>Sales</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean</td>
<td>14</td>
<td>130</td>
</tr>
<tr class="even">
<td>Standard Error</td>
<td>2.512</td>
<td>13.220</td>
</tr>
<tr class="odd">
<td>Median</td>
<td>14</td>
<td>127.5</td>
</tr>
<tr class="even">
<td>Mode</td>
<td>8</td>
<td>N/A</td>
</tr>
<tr class="odd">
<td>Standard Deviation</td>
<td>7.944</td>
<td>41.806</td>
</tr>
<tr class="even">
<td>Sample Variance</td>
<td>63.111</td>
<td>1747.778</td>
</tr>
<tr class="odd">
<td>Kurtosis</td>
<td>-1.332</td>
<td>-0.033</td>
</tr>
<tr class="even">
<td>Skewness</td>
<td>0</td>
<td>-0.014</td>
</tr>
<tr class="odd">
<td>Range</td>
<td>24</td>
<td>144</td>
</tr>
<tr class="even">
<td>Minimum</td>
<td>2</td>
<td>58</td>
</tr>
<tr class="odd">
<td>Maximum</td>
<td>26</td>
<td>202</td>
</tr>
<tr class="even">
<td>Sum</td>
<td>140</td>
<td>1300</td>
</tr>
<tr class="odd">
<td>Count</td>
<td>10</td>
<td>10</td>
</tr>
<tr class="even">
<td>Confidence Level (95%)</td>
<td>5.683</td>
<td>29.907</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="linear-regression-example-3" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-3">Linear Regression: Example</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p><br></p>
</section>
<section id="linear-regression-example-excel-1" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-excel-1">Linear Regression: Example Excel</h2>
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="nonincremental">
<p><br></p>
<ul>
<li><p>Producing a Scatter Diagram</p>
<ul>
<li>Step 1: Select cells B2:C11</li>
<li>Step 2: Click the <strong>Insert</strong> tab on the Ribbon</li>
<li>Step 3: In the Charts group, select <strong>Insert Scatter (X,Y)</strong> or <strong>Bubble Chart</strong></li>
<li>Step 4: When the list of scatter diagram subtypes appears, select <strong>Scatter</strong> (chart in upper left corner)</li>
</ul></li>
</ul>
</div>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="fragment">
<div style="font-size: 80%;">
<div class="nonincremental">
<ul>
<li><p>Editing a Scatter Diagram</p>
<ul>
<li>Step 1: Click the <strong>Chart Title</strong> and replace it with <em>Armand’s Pizza Parlors</em></li>
<li>Step 2: Click the <strong>Chart Elements</strong> button</li>
<li>Step 3: When the list of chart elements appears:
<ul>
<li>Click <strong>Axis Titles</strong> (creates placeholders for titles)</li>
<li>Click <strong>Gridlines</strong> (to deselect gridlines option)</li>
<li>Click <strong>Trendline</strong></li>
</ul></li>
<li>Step 4: Click the horizontal <strong>Axis Title</strong> and replace it with <em>Student population (1000s)</em></li>
<li>Step 5: Click the <strong>Vertical (Value) Axis Title</strong> and replace it with <em>Quarterly Sales ($1000s)</em></li>
<li>Step 6: Select the <strong>Format Trendline</strong> option</li>
<li>Step 7: When the Format Trendline dialog box appears:
<ul>
<li>Select <strong>Display equation on chart</strong></li>
<li>Click the <strong>Fill &amp; Line</strong> button</li>
<li>In the <strong>Dash type</strong> box, select <strong>Solid</strong></li>
<li>Close the <strong>Format Trendline</strong> dialog box</li>
</ul></li>
</ul></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="linear-regression-example-4" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-4">Linear Regression: Example</h2>
<div style="font-size: 80%;">
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>i</th>
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(y_i\)</span></th>
<th><span class="math inline">\(x_i - \bar{x}\)</span></th>
<th><span class="math inline">\(y_i - \bar{y}\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})(y_i - \bar{y})\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
<th><span class="math inline">\((y_i - \bar{y})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>58</td>
<td>-12</td>
<td>-72</td>
<td>864</td>
<td>144</td>
<td>5184</td>
</tr>
<tr class="even">
<td>2</td>
<td>6</td>
<td>105</td>
<td>-8</td>
<td>-25</td>
<td>200</td>
<td>64</td>
<td>625</td>
</tr>
<tr class="odd">
<td>3</td>
<td>8</td>
<td>88</td>
<td>-6</td>
<td>-42</td>
<td>252</td>
<td>36</td>
<td>1764</td>
</tr>
<tr class="even">
<td>4</td>
<td>8</td>
<td>118</td>
<td>-6</td>
<td>-12</td>
<td>72</td>
<td>36</td>
<td>144</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>117</td>
<td>-2</td>
<td>-13</td>
<td>26</td>
<td>4</td>
<td>169</td>
</tr>
<tr class="even">
<td>6</td>
<td>16</td>
<td>137</td>
<td>2</td>
<td>7</td>
<td>14</td>
<td>4</td>
<td>49</td>
</tr>
<tr class="odd">
<td>7</td>
<td>20</td>
<td>157</td>
<td>6</td>
<td>27</td>
<td>162</td>
<td>36</td>
<td>729</td>
</tr>
<tr class="even">
<td>8</td>
<td>20</td>
<td>169</td>
<td>6</td>
<td>39</td>
<td>234</td>
<td>36</td>
<td>1521</td>
</tr>
<tr class="odd">
<td>9</td>
<td>22</td>
<td>149</td>
<td>8</td>
<td>19</td>
<td>152</td>
<td>64</td>
<td>361</td>
</tr>
<tr class="even">
<td>10</td>
<td>26</td>
<td>202</td>
<td>12</td>
<td>72</td>
<td>864</td>
<td>144</td>
<td>5184</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>140</strong></td>
<td><strong>1300</strong></td>
<td>-</td>
<td>-</td>
<td><strong>2840</strong></td>
<td><strong>568</strong></td>
<td><strong>15730</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Sample correlation:</p>
<p><span class="math display">\[
r_{xy} = \frac{\sum(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum(x_i - \bar{x})^2 \sum(y_i - \bar{y})^2}} = \frac{2840}{\sqrt{568 \times 15730}} = 0.9501
\]</span></p>
<center>
<code>= correl(x-array, y-array)</code>
</center>
</div>
</div>
</section>
<section id="linear-regression-example-5" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression-example-5">Linear Regression: Example</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li>Slope for the Estimated Regression Equation</li>
</ul>
<p><span class="math display">\[
b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2} = \frac{2840}{568} = 5
\]</span></p>
<ul>
<li>y-Intercept for the Estimated Regression Equation</li>
</ul>
<p><span class="math display">\[
b_0 = \bar{y} - b_1 \bar{x} = 130 - 5(14) = 60
\]</span></p>
<ul>
<li>Estimated Regression Equation</li>
</ul>
<p><span class="math display">\[
\hat{y} = 60 + 5x
\]</span></p>
</div>
</section>
<section id="remarks" class="level2">
<h2 class="anchored" data-anchor-id="remarks">Remarks</h2>
<p><br></p>
<div style="font-size: 80%;">
<div class="nonincremental">
<p><span class="math display">\[
b_1 = \frac{\sum (x_i - \bar{x})(y_i - \bar{y})}{\sum (x_i - \bar{x})^2} = \frac{\sum (x_i - \bar{x})(y_i - \bar{y}) / (n - 1)}{\sum (x_i - \bar{x})^2 / (n - 1)} = \frac{s_{xy}}{s_x^2}
\]</span></p>
<p><span class="math display">\[
= \frac{s_{xy}}{s_x s_y} \cdot \frac{s_y}{s_x} = r_{xy} \frac{s_y}{s_x}
\]</span></p>
<p><span class="math inline">\(b_1\)</span>, <span class="math inline">\(s_{xy}\)</span>, and <span class="math inline">\(r_{xy}\)</span> have the same signs, reflecting the relationship’s direction between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p>
</div>
</div>
<div style="font-size: 70%;">
<div class="nonincremental">
<ul>
<li><p><span class="math inline">\(b_1\)</span>: Slope of the regression line, indicating the change in <span class="math inline">\(y\)</span> for a unit change in <span class="math inline">\(x\)</span>.</p></li>
<li><p><span class="math inline">\(\sum (x_i - \bar{x})(y_i - \bar{y})\)</span>: Numerator for covariance, showing the joint deviation of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> from their means.</p></li>
<li><p><span class="math inline">\(\sum (x_i - \bar{x})^2\)</span>: Denominator representing variance of <span class="math inline">\(x\)</span>.</p></li>
<li><p><span class="math inline">\(s_{xy}\)</span>: Sample covariance, indicating how <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> vary together.</p></li>
<li><p><span class="math inline">\(s_x^2\)</span>: Sample variance of <span class="math inline">\(x\)</span>, measuring the dispersion of <span class="math inline">\(x\)</span> around its mean.</p></li>
<li><p><span class="math inline">\(s_x\)</span> and <span class="math inline">\(s_y\)</span>: Standard deviations of <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>, showing spread around their means.</p></li>
<li><p><span class="math inline">\(r_{xy}\)</span>: Correlation coefficient, measuring strength and direction of the linear relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>.</p></li>
</ul>
</div>
</div>
</section>
<section id="partition-of-total-variation" class="level2">
<h2 class="anchored" data-anchor-id="partition-of-total-variation">Partition of Total Variation</h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_partitition.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="partition-of-total-variation-1" class="level2">
<h2 class="anchored" data-anchor-id="partition-of-total-variation-1">Partition of Total Variation</h2>
<div class="nonincremental">
<ul>
<li><strong>Prediction equation:</strong> <span class="math inline">\(\hat{y} = 60 + 5x\)</span></li>
<li><strong>For Observation #1</strong> <span class="math inline">\((x = 2, y = 58)\)</span>: <span class="math inline">\(\hat{y} = 60 + 5(2) = 70\)</span>
<ul>
<li>Unexplained error/residual = <span class="math inline">\(y - \hat{y} = 58 - 70 = -12\)</span></li>
</ul></li>
</ul>
<p><br></p>
<ul>
<li><strong>Note:</strong></li>
</ul>
<p><span class="math display">\[
y - \bar{y} = (\hat{y} - \bar{y}) + (y - \hat{y})
\]</span></p>
<p><span class="math display">\[
58 - 130 = (70 - 130) + (58 - 70)
\]</span></p>
<p><span class="math display">\[
\text{Total} = \text{Explained} + \text{Unexplained}
\]</span></p>
</div>
</section>
<section id="partition-of-total-variation-2" class="level2">
<h2 class="anchored" data-anchor-id="partition-of-total-variation-2">Partition of Total Variation</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span></th>
<th><span class="math inline">\(x_i\)</span></th>
<th>Observed Y</th>
<th>Predicted Y</th>
<th>Total</th>
<th>Explained</th>
<th>Unexplained</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>58</td>
<td>70</td>
<td>-72</td>
<td>-60</td>
<td>-12</td>
</tr>
<tr class="even">
<td>2</td>
<td>6</td>
<td>105</td>
<td>90</td>
<td>-25</td>
<td>-40</td>
<td>15</td>
</tr>
<tr class="odd">
<td>3</td>
<td>8</td>
<td>88</td>
<td>100</td>
<td>-42</td>
<td>-30</td>
<td>-12</td>
</tr>
<tr class="even">
<td>4</td>
<td>8</td>
<td>118</td>
<td>100</td>
<td>-12</td>
<td>-30</td>
<td>18</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>117</td>
<td>120</td>
<td>-13</td>
<td>-10</td>
<td>-3</td>
</tr>
<tr class="even">
<td>6</td>
<td>16</td>
<td>137</td>
<td>140</td>
<td>7</td>
<td>10</td>
<td>-3</td>
</tr>
<tr class="odd">
<td>7</td>
<td>20</td>
<td>157</td>
<td>160</td>
<td>27</td>
<td>30</td>
<td>-3</td>
</tr>
<tr class="even">
<td>8</td>
<td>20</td>
<td>169</td>
<td>160</td>
<td>39</td>
<td>30</td>
<td>9</td>
</tr>
<tr class="odd">
<td>9</td>
<td>22</td>
<td>149</td>
<td>170</td>
<td>19</td>
<td>40</td>
<td>-21</td>
</tr>
<tr class="even">
<td>10</td>
<td>26</td>
<td>202</td>
<td>190</td>
<td>72</td>
<td>60</td>
<td>12</td>
</tr>
<tr class="odd">
<td></td>
<td>Mean Y</td>
<td>130</td>
<td>Sum of square</td>
<td>15730</td>
<td>14200</td>
<td>1530</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
<td>SST</td>
<td>SSR</td>
<td>SSE</td>
</tr>
</tbody>
</table>
</section>
<section id="derivation-of-the-total-sum-of-squares-sst" class="level2">
<h2 class="anchored" data-anchor-id="derivation-of-the-total-sum-of-squares-sst">Derivation of the Total Sum of Squares (SST)</h2>
<div style="font-size: 60%;">
<p>In the context of simple linear regression, the Total Sum of Squares (SST) is defined as the sum of the squared deviations of the observed <span class="math inline">\(y\)</span> values from their sample mean <span class="math inline">\(\bar{y}\)</span>:</p>
<p><span class="math display">\[
SST = \sum_{i=1}^{n} (y_i - \bar{y})^2.
\]</span></p>
<p>It is also possible to compute the SST with the following:</p>
<p><span class="math display">\[
SST = (n-1)s^2_y,
\]</span></p>
<p><strong>Derivation</strong></p>
<p>Recall that the sample variance of <span class="math inline">\(y\)</span>, denoted <span class="math inline">\(s^2_y\)</span>, is defined as:</p>
<p><span class="math display">\[
s^2_y = \frac{1}{n-1}\sum_{i=1}^{n} (y_i - \bar{y})^2.
\]</span></p>
<p>This definition uses <span class="math inline">\(n-1\)</span> in the denominator to provide an unbiased estimator of the population variance.</p>
<p>By multiplying both sides of the sample variance definition by <span class="math inline">\(n-1\)</span>, we obtain:</p>
<p><span class="math display">\[
(n-1)s^2_y = \sum_{i=1}^{n} (y_i - \bar{y})^2.
\]</span></p>
<p>Recognizing that the right-hand side is exactly the definition of <span class="math inline">\(SST\)</span>, we conclude:</p>
<p><span class="math display">\[
SST = (n-1)s^2_y.
\]</span></p>
<p>Thus, the derivation relies on the definition of sample variance, and the result follows directly from the algebraic manipulation.</p>
</div>
</section>
</section>
<section id="coefficient-of-determination" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Coefficient of Determination</h1>
<section id="coefficient-of-determination-1" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination-1">Coefficient of Determination</h2>
<div class="nonincremental">
<ul>
<li><strong>Relationship Among SST, SSR, SSE</strong></li>
</ul>
<p><span class="math display">\[
\text{SST} = \text{SSR} + \text{SSE}
\]</span></p>
<p><span class="math display">\[
\sum(y_i - \bar{y})^2 = \sum(\hat{y}_i - \bar{y})^2 + \sum(y_i - \hat{y}_i)^2
\]</span></p>
<p><span class="math display">\[
\text{Degrees of freedom:} \quad n-1 \quad\quad\quad\quad\quad 1 \quad\quad\quad\quad\quad n-2 \quad\quad\quad\quad\quad\quad\quad\quad\quad
\]</span></p>
<p><strong>where:</strong></p>
<ul>
<li>SST = total sum of squares (<em>Total variation</em>)</li>
<li>SSR = sum of squares due to regression (<em>Explained variation</em>)</li>
<li>SSE = sum of squares due to error (<em>Unexplained variation</em>)</li>
</ul>
</div>
</section>
<section id="coefficient-of-determination-2" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination-2">Coefficient of Determination</h2>
<div class="nonincremental">
<ul>
<li>The <strong>coefficient of determination</strong> is:</li>
</ul>
<p><span class="math display">\[
R^2 = \frac{\text{Explained variation}}{\text{Total variation}} = \frac{\text{SSR}}{\text{SST}}
\]</span></p>
<p><strong>where:</strong></p>
<ul>
<li>SSR = sum of squares due to regression</li>
<li>SST = total sum of squares</li>
</ul>
</div>
</section>
<section id="coefficient-of-determination-3" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination-3">Coefficient of Determination</h2>
<p><strong>Example:</strong> Armand’s Pizza Parlor Restaurants</p>
<div class="nonincremental">
<p><span class="math display">\[
R^2 = \frac{\text{SSR}}{\text{SST}} = \frac{14200}{15730} = 0.9027 = 90.27\%
\]</span></p>
<p><span class="math display">\[
R^2 = 1 - \frac{\text{SSE}}{\text{SST}} = 1 - \frac{1530}{15730} = 1 - 0.973 = 90.27\%
\]</span></p>
<ul>
<li>The regression relationship is very strong;</li>
<li>90.27% of the variability in the sales can be explained by (the variability of) the size of the student population through the proposed linear relationship between them.</li>
</ul>
</div>
</section>
<section id="coefficient-of-determination-excel" class="level2">
<h2 class="anchored" data-anchor-id="coefficient-of-determination-excel">Coefficient of Determination: Excel</h2>
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="nonincremental">
<p><br></p>
<ul>
<li><p><strong>Adding</strong> <span class="math inline">\(R^2\)</span> Value to Scatter Diagram</p>
<ul>
<li>Step 1: Right-click on the trendline and select the <strong>Format Trendline</strong> option</li>
<li>Step 2: When the Format Trendline dialog box appears:
<ul>
<li>Select <strong>Display R-squared on chart</strong></li>
<li>Close the <strong>Format Trendline</strong> dialog box</li>
</ul></li>
</ul></li>
</ul>
</div>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="fragment">
<div style="font-size: 80%;">
<div class="nonincremental">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_r2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="sample-correlation-coefficient" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-coefficient">Sample Correlation Coefficient</h2>
<div class="nonincremental">
<p><span class="math display">\[
r_{xy} = (\text{sign of } b_1) \sqrt{\text{Coefficient of Determination}}
\]</span></p>
<p><span class="math display">\[
r_{xy} = (\text{sign of } b_1) \sqrt{R^2}
\]</span></p>
<p><strong>where:</strong></p>
<ul>
<li><span class="math inline">\(b_1\)</span> = the slope of the estimated regression equation <span class="math inline">\(\hat{y} = b_0 + b_1x\)</span></li>
</ul>
<p><strong>Only in simple regression.</strong></p>
</div>
</section>
<section id="sample-correlation-coefficient-1" class="level2">
<h2 class="anchored" data-anchor-id="sample-correlation-coefficient-1">Sample Correlation Coefficient</h2>
<div class="nonincremental">
<p><strong>Example:</strong> Armand’s Pizza Parlor Restaurants</p>
<p><span class="math display">\[
r_{xy} = (\text{sign of } b_1) \sqrt{R^2}
\]</span></p>
<p>The sign of <span class="math inline">\(b_1\)</span> in the equation <span class="math inline">\(\hat{y} = 10 + 5x\)</span> is “+”.</p>
<p><span class="math display">\[
r_{xy} = +\sqrt{0.9027}
\]</span></p>
<p><span class="math display">\[
r_{xy} = +0.9501
\]</span></p>
</div>
</section>
</section>
<section id="model-assumptions" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Model Assumptions</h1>
<section id="assumptions-about-the-error-term-epsilon" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-about-the-error-term-epsilon">Assumptions About the Error Term <span class="math inline">\(\epsilon\)</span></h2>
<ol type="1">
<li><p>The error term <span class="math inline">\(\epsilon\)</span> is a random variable with a mean or expected value of zero; that is, <span class="math inline">\(E(\epsilon) = 0\)</span>.</p>
<ul>
<li><strong>Implication</strong>: <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are constants; therefore <span class="math inline">\(E(\beta_0) = \beta_0\)</span> and <span class="math inline">\(E(\beta_1) = \beta_1\)</span>; thus, for a given value of <span class="math inline">\(x\)</span>, the expected value of <span class="math inline">\(y\)</span> is:</li>
</ul></li>
</ol>
<div class="fragment">
<p><span class="math display">\[
   E(y) = \beta_0 + \beta_1x
\]</span></p>
</div>
<ol start="2" type="1">
<li><p>The variance of <span class="math inline">\(\epsilon\)</span>, denoted by <span class="math inline">\(\sigma^2\)</span>, is the same for all values of <span class="math inline">\(x\)</span>.</p>
<ul>
<li><strong>Implication</strong>: The variance of <span class="math inline">\(y\)</span> about the regression line equals <span class="math inline">\(\sigma^2\)</span> and is the same for all values of <span class="math inline">\(x\)</span>.</li>
</ul></li>
<li><p>The values of <span class="math inline">\(\epsilon\)</span> are independent.</p>
<ul>
<li><strong>Implication</strong>: The value of <span class="math inline">\(\epsilon\)</span> for a particular value of <span class="math inline">\(x\)</span> is not related to the value of <span class="math inline">\(\epsilon\)</span> for any other value of <span class="math inline">\(x\)</span>; thus, the value of <span class="math inline">\(y\)</span> for a particular value of <span class="math inline">\(x\)</span> is not related to the value of <span class="math inline">\(y\)</span> for any other value of <span class="math inline">\(x\)</span>.</li>
</ul></li>
<li><p>The error term <span class="math inline">\(\epsilon\)</span> is a normally distributed random variable for all values of <span class="math inline">\(x\)</span>.</p>
<ul>
<li><strong>Implication</strong>: Because <span class="math inline">\(y\)</span> is a linear function of <span class="math inline">\(\epsilon\)</span>, <span class="math inline">\(y\)</span> is also a normally distributed random variable for all values of <span class="math inline">\(x\)</span>.</li>
</ul></li>
</ol>
</section>
<section id="assumptions-about-the-error-term-epsilon-1" class="level2">
<h2 class="anchored" data-anchor-id="assumptions-about-the-error-term-epsilon-1">Assumptions About the Error Term <span class="math inline">\(\epsilon\)</span></h2>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/residuals_assumption.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p><br></p>
</section>
</section>
<section id="testing-for-significance" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Testing for Significance</h1>
<section id="testing-for-significance-1" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-significance-1">Testing for Significance</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><p>To test for a significant regression relationship, we must conduct a hypothesis test to determine whether the unknown <span class="math inline">\(\beta_1\)</span> is zero.</p></li>
<li><p>Two equivalent Tests are commonly used in simple regression:</p>
<ul>
<li><span class="math inline">\(t\)</span> Test<br>
</li>
<li><span class="math inline">\(F\)</span> test</li>
</ul></li>
<li><p>Both the <span class="math inline">\(t\)</span> test and <span class="math inline">\(F\)</span> test require an estimate of the unknown error variance <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ul>
</div>
</section>
<section id="testing-for-significance-2" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-significance-2">Testing for Significance</h2>
<p><br></p>
<div class="nonincremental">
<p>Idea: <strong>Estimating the population error variance</strong> (<span class="math inline">\(\sigma^2\)</span>) <strong>by the sample residual variance</strong> (denoted by <span class="math inline">\(s^2\)</span> or MSE).</p>
<p>The mean square error (MSE), or <span class="math inline">\(s^2\)</span> is:</p>
<p><span class="math display">\[
s^2 = \text{MSE} = \frac{\text{SSE}}{(n-2)}, \quad \text{SSE = Sum of Squared Errors (unexplained variation).}
\]</span></p>
<p>where:</p>
<p><span class="math display">\[
\text{SSE} = \sum e_i^2 = \sum (y_i - \hat{y}_i)^2
\]</span></p>
</div>
</section>
<section id="testing-for-significance-3" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-significance-3">Testing for Significance</h2>
<div class="nonincremental">
<ul>
<li><strong>An Estimate of</strong> <span class="math inline">\(\sigma\)</span>
<ul>
<li>To estimate <span class="math inline">\(\sigma\)</span>, we take the square root of <span class="math inline">\(s^2\)</span>.</li>
<li>The resulting <span class="math inline">\(s\)</span> is called the standard error (of the estimate).</li>
</ul></li>
</ul>
<p><span class="math display">\[
s = \sqrt{MSE} = \sqrt{\frac{SSE}{n - 2}} = \sqrt{\frac{\sum (y_i - \hat{y}_i)^2}{n - 2}}
\]</span></p>
</div>
</section>
<section id="testing-for-overall-significance-f-test" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-overall-significance-f-test">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</h2>
<div class="nonincremental">
<div class="r-fit-text">
<ul>
<li><p><strong>Hypotheses</strong></p>
<p><span class="math display">\[ H_0 : \beta_1 = 0 \quad\]</span> The proposed linear model is insignificant; No linear relationship; the predictor is insignificant; the predictor explains no variation in the response.</p>
<p><span class="math display">\[ H_a : \beta_1 \neq 0 \]</span></p></li>
<li><p><strong>Test Statistic</strong></p></li>
</ul>
<p><span class="math display">\[
F = \frac{SSR / 1}{SSE / (n-2)} = \frac{MSR}{MSE} \quad \text{follows } F(1, n-2), \text{ if } H_0 \text{ is true.}
\]</span> where</p>
<ul>
<li><strong>SSR (Sum of Squares for Regression)</strong>: measures how much of the variation in the dependent variable is explained by the independent variable(s).</li>
<li><strong>MSR (Mean Square Regression)</strong>: is the average variation explained by the model per degree of freedom for the regression.In the case above, we have only one independent variable as the degree of freedom for the regression (denominator).</li>
<li><strong>SSE (Sum of Squares for Error/Residuals)</strong>: measures the variation in the response variable that is not explained by the model.</li>
<li><strong>MSE (Mean Square Error)</strong>: is the average variation that remains unexplained by the model, per degree of freedom for the error. The degrees of freedom for the error is the number of observations (<span class="math inline">\(n\)</span>) in the data set minus the number of parameters being estimated (<span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>).</li>
</ul>
</div>
</div>
</section>
<section id="testing-for-overall-significance-f-test-1" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-overall-significance-f-test-1">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</h2>
<div class="nonincremental">
<ul>
<li><p><strong>Decision Rules</strong> <em>(right-tail)</em>:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p\text{-value} \leq \alpha\)</span>, or <span class="math inline">\(F \geq F_{\alpha, 1, n-2}\)</span></li>
</ul></li>
</ul>
<p><br></p>
<p>where:</p>
<ul>
<li><p><span class="math inline">\(F_{\alpha, 1, n-2}\)</span> is based on an <span class="math inline">\(F\)</span> distribution with 1 degree of freedom in the numerator and <span class="math inline">\(n - 2\)</span> degrees of freedom in the denominator.</p></li>
<li><p><span class="math inline">\(F_{\alpha, 1, n-2} = F.\text{INV}(1-\alpha, 1, n - 2)\)</span></p></li>
</ul>
</div>
</section>
<section id="testing-for-overall-significance-f-test-2" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-overall-significance-f-test-2">Testing for Overall Significance: <span class="math inline">\(F\)</span> Test</h2>
<div class="nonincremental">
<ul>
<li>Compute the value of the test statistic.</li>
</ul>
<p><span class="math display">\[
F = \frac{SSR / 1}{SSE / (n-2)} = \frac{14,200 / 1}{1,530 / (10-2)} = 74.25
\]</span></p>
<p><br></p>
<ul>
<li><p><strong>Decision.</strong></p>
<ul>
<li><p><span class="math inline">\(F_{\alpha} = F.\text{INV}(0.99,1,8) = 11.26\)</span> and <span class="math inline">\(F = 74.25 &gt; 11.26.\)</span> We reject <span class="math inline">\(H_0.\)</span></p></li>
<li><p><span class="math inline">\(p\text{-value} = 1 - F.\text{DIST}(74.25,1,8, \text{TRUE}) \approx 0.000 &lt; 1\% = \alpha\)</span></p></li>
</ul></li>
</ul>
<center>
<div class="red">
<p>The statistical evidence is sufficient to conclude that a significant relationship exists between the size of the student population and quarterly sales. The significance level is <span class="math inline">\(\alpha = 1\%\)</span>.</p>
</div>
</center>
</div>
</section>
<section id="testing-for-individual-significance-t-test" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-individual-significance-t-test">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</h2>
<div style="font-size: 70%;">
<div class="nonincremental">
<div class="red">
<p>In regression, <span class="math inline">\(b_1\)</span> follows a normal distribution with mean <span class="math inline">\(\beta_1\)</span>.</p>
</div>
<ul>
<li><p><strong>Hypotheses</strong></p>
<p><span class="math inline">\(H_0 : \beta_1 = 0 \quad (\text{Independent variable x is insignificant})\)</span></p>
<p><span class="math inline">\(H_a : \beta_1 \neq 0\)</span></p></li>
<li><p><strong>Test Statistic</strong></p></li>
</ul>
<p><span class="math display">\[
t = \frac{b_1 - 0}{s_{b_1}},
\]</span> where <span class="math inline">\(s_{b_1}\)</span> is the <strong>standard error</strong> of the slope estimate <span class="math inline">\(b_1\)</span>, i.e., an estimate of the standard deviation of the sampling distribution of <span class="math inline">\(b_1\)</span>. It is not the population standard deviation; it is the estimated uncertainty in the slope due to sampling. It follows <span class="math inline">\(t(n-2)\)</span>, if <span class="math inline">\(H_0\)</span> is true.</p>
<p><span class="math display">\[
s_{b_1} = \frac{s}{\sqrt{\sum(x_i - \bar{x})^2}} = \frac{\sqrt{\frac{\sum (y_i - \hat{y}_i)^2}{n - 2}}}{\sqrt{\sum(x_i - \bar{x})^2}}= \sqrt{\frac{\sum (Y_i - \hat{Y}_i)^2}{(n - 2)\,\sum (X_i - \bar{X})^2}}
\]</span></p>
<p>if we denote <span class="math inline">\(\text{MSE} = \frac{\sum (Y_i - \hat{Y}_i)^2}{n - 2}\)</span> (the <strong>mean squared error</strong>), then:</p>
<p><span class="math display">\[
s_{b_1} = \sqrt{\frac{\text{MSE}}{\sum (X_i - \bar{X})^2}}.
\]</span></p>
</div>
</div>
</section>
<section id="testing-for-individual-significance-t-test-1" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-individual-significance-t-test-1">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</h2>
<div class="nonincremental">
<p><br></p>
<ul>
<li><p><strong>Decision Rules</strong> <em>(two-tail)</em>:</p>
<ul>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(p\text{-value} \leq \alpha\)</span></li>
<li>Reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(t \leq -t_{\alpha/2,n-2}\)</span> or <span class="math inline">\(t \geq t_{\alpha/2,n-2}\)</span> (i.e., <span class="math inline">\(|t| &gt; t_{\alpha/2,n-2}\)</span>)</li>
</ul></li>
</ul>
<p>where the critical value, <span class="math inline">\(t_{\alpha/2, n-2}\)</span>, is based on a <span class="math inline">\(t\)</span> distribution with <span class="math inline">\(n - 2\)</span> df.</p>
</div>
</section>
<section id="testing-for-individual-significance-t-test-2" class="level2">
<h2 class="anchored" data-anchor-id="testing-for-individual-significance-t-test-2">Testing for Individual Significance: <span class="math inline">\(t\)</span> Test</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li>Compute the value of the test statistic:</li>
</ul>
<p><span class="math display">\[
t = \frac{b_1 - 0}{s_{b_1}} = \frac{5 - 0}{.5803} = 8.62
\]</span> <br></p>
<ul>
<li><p><strong>Decision:</strong></p>
<ul>
<li><span class="math inline">\(t_{0.01/2, 8} = T.\text{INV}(0.995,8) = 3.355\)</span> provides an area of 0.005 in the upper tail of a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</li>
<li>Because <span class="math inline">\(|t| = 8.62 &gt; 3.355\)</span>, we can reject <span class="math inline">\(H_0\)</span> at <span class="math inline">\(\alpha = 1\%\)</span>.</li>
<li><span class="math inline">\(p\text{-value} = 2*(1-T.\text{DIST}(8.62,10-2,\text{TRUE})) \approx 0.000&lt; 1\%\)</span>.</li>
</ul>
<p>We can reject <span class="math inline">\(H_0\)</span>.</p></li>
</ul>
</div>
</section>
<section id="confidence-interval-for-beta_1" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-beta_1">Confidence Interval for <span class="math inline">\(\beta_1\)</span></h2>
<p><br></p>
<p><br></p>
<p>We can use a 99% confidence interval for <span class="math inline">\(\beta_1\)</span> to test the hypotheses just used in the <em>t</em> test.</p>
<p><span class="math inline">\(H_0\)</span> is rejected if the hypothesized value of <span class="math inline">\(\beta_1\)</span> is not included in the corresponding confidence interval for <span class="math inline">\(\beta_1\)</span>.</p>
</section>
<section id="confidence-interval-for-beta_1-1" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-beta_1-1">Confidence Interval for <span class="math inline">\(\beta_1\)</span></h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li>The form of a confidence interval for <span class="math inline">\(\beta_1\)</span> is:</li>
</ul>
<p><span class="math display">\[
b_1 \pm t_{\alpha/2, n-2} s_{b_1}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(b_1\)</span> is the point estimator,</li>
<li><span class="math inline">\(t_{\alpha/2, n-2} s_{b_1}\)</span> is the margin of error (MOE),</li>
<li><span class="math inline">\(t_{\alpha/2, n-2}\)</span> is the <strong><em>t</em> critical value</strong> providing an upper-tail area of <span class="math inline">\(\alpha/2\)</span> in a <em>t</em> distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</li>
<li><span class="math inline">\(s_{b_1}\)</span> is the <strong>standard error</strong> of the slope estimate <span class="math inline">\(b_1\)</span>, i.e., an estimate of the standard deviation of the sampling distribution of <span class="math inline">\(b_1\)</span>. It is not the population standard deviation; it is the estimated uncertainty in the slope due to sampling.</li>
</ul>
</div>
</section>
<section id="confidence-interval-for-beta_1-2" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-beta_1-2">Confidence Interval for <span class="math inline">\(\beta_1\)</span></h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><strong>99% Confidence Interval for</strong> <span class="math inline">\(\beta_1\)</span>:</li>
</ul>
<p><span class="math display">\[
b_1 \pm t_{\alpha/2} s_{b_1} = 5 \pm 3.355(.5803) = 5 \pm 1.95
\]</span></p>
<p>or 3.05 to 6.95</p>
<ul>
<li><strong>Conclusion:</strong> 0 is not included in the 99% confidence interval. Reject <span class="math inline">\(H_0\)</span> at <span class="math inline">\(\alpha\)</span> = 1%.</li>
</ul>
</div>
</section>
<section id="some-cautions-about-the-interpretation-of-significance-tests" class="level2">
<h2 class="anchored" data-anchor-id="some-cautions-about-the-interpretation-of-significance-tests">Some Cautions about the Interpretation of Significance Tests</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><p>Rejecting <span class="math inline">\(H_0: \beta_1 = 0\)</span> and concluding that the relationship between x and y is significant does not enable us to conclude that a <strong>cause-and-effect relationship</strong> is present between x and y.</p></li>
<li><p>Because we <strong>are able to</strong> reject <span class="math inline">\(H_0: \beta_1 = 0\)</span> and demonstrate statistical significance does not enable us to conclude that there is a <strong>linear relationship</strong> between x and y.</p></li>
</ul>
</div>
</section>
</section>
<section id="excels-regression-tool" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Excel’s Regression Tool</h1>
<section id="excels-regression-tool-1" class="level2">
<h2 class="anchored" data-anchor-id="excels-regression-tool-1">Excel’s Regression Tool</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><p>Excel also has a comprehensive tool in its Data Analysis package called <strong>Regression</strong>.</p></li>
<li><p>The Regression tool can be used to perform a <strong>complete regression analysis</strong>.</p></li>
</ul>
</div>
</section>
<section id="using-excels-regression-tool" class="level2">
<h2 class="anchored" data-anchor-id="using-excels-regression-tool">Using Excel’s Regression Tool</h2>
<center>
<strong>Performing the Regression Analysis</strong>
</center>
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="nonincremental">
<p><br></p>
<ul>
<li><p><strong>Step 1</strong> Click the <strong>DATA</strong> tab on the Ribbon</p></li>
<li><p><strong>Step 2</strong> In the <strong>Analyze</strong> group, click <strong>Data Analysis</strong></p></li>
<li><p><strong>Step 3</strong> Choose <strong>Regression</strong> from the list of Analysis Tools</p></li>
</ul>
</div>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<div class="fragment">
<div style="font-size: 80%;">
<div class="nonincremental">
<p><br></p>
<ul>
<li><p><strong>Step 4</strong> When the Regression dialog box appears:</p>
<ul>
<li>Enter <strong>C1:C11</strong> in the <strong>Input Y Range</strong> box</li>
<li>Enter <strong>B1:B11</strong> in the <strong>Input X Range</strong> box</li>
<li>Select the check box for <strong>Labels</strong></li>
<li>Select the check box for <strong>Confidence Level</strong></li>
<li>Enter <strong>99</strong> in the <strong>Confidence Level</strong> box</li>
<li>Select <strong>Output Range</strong></li>
<li>Enter <strong>A13</strong> in the <strong>Output Range</strong> box</li>
<li>Click <strong>OK</strong></li>
</ul></li>
</ul>
<p><br></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="using-excels-regression-tool-1" class="level2">
<h2 class="anchored" data-anchor-id="using-excels-regression-tool-1">Using Excel’s Regression Tool</h2>
<p><br></p>
<p><strong>Example:</strong> Armand’s Pizza Parlors: Regression tool dialog box</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_reg_excel.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="using-excels-regression-tool-2" class="level2">
<h2 class="anchored" data-anchor-id="using-excels-regression-tool-2">Using Excel’s Regression Tool</h2>
<p><br></p>
<p><strong>Example:</strong> Armand’s Pizza Parlors: Regression tool dialog box</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_reg_excel_output.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="using-excels-regression-tool-3" class="level2">
<h2 class="anchored" data-anchor-id="using-excels-regression-tool-3">Using Excel’s Regression Tool</h2>
<div class="r-fit-text">
<div class="nonincremental">
<div class="columns">
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p><strong>Regression Statistics</strong>:</p>
<ul>
<li><p><strong>Multiple R</strong>: 0.9501. Indicates a strong positive correlation between observed and predicted values.</p></li>
<li><p><strong>R Square (Coefficient of Determination)</strong>: Approximately 90.27% of the variance in the dependent variable (Sales) is explained by the independent variable (Population).</p></li>
<li><p><strong>Adjusted R Square</strong>: 0.8906. Adjusts the R Square for the number of predictors, providing a more accurate measure.</p></li>
<li><p><strong>Standard Error</strong>: 13.8293. Measures the typical distance that the observed values fall from the regression line.</p></li>
</ul>
</div>
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p><strong>ANOVA</strong></p>
<ul>
<li><strong>Regression SS</strong>: 14200. Variability explained by the model.
<ul>
<li><strong>Residual SS</strong>: 1530. Variability not explained by the model.</li>
<li><strong>F-Statistic</strong>: 74.2484. Indicates the model is statistically significant.</li>
<li><strong>Significance F</strong>: 2.55E-05. <span class="math inline">\(p\)</span>-value indicating strong evidence against the null hypothesis.</li>
</ul></li>
</ul>
</div>
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<p><strong>Model Results</strong></p>
<ul>
<li><p><strong>Coefficients</strong>:</p>
<ul>
<li><strong>Intercept</strong>: 60 (p-value: 0.0002)<br>
</li>
<li><strong>Population</strong>: 5 (p-value: 2.55E-05)<br>
</li>
<li>Both coefficients are statistically significant.</li>
</ul></li>
<li><p><strong>Confidence Intervals</strong>:</p>
<ul>
<li><strong>95% CI for Intercept</strong>: [38.7247, 81.2753]</li>
<li><strong>95% CI for Population</strong>: [3.6619, 6.3381]</li>
</ul></li>
</ul>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="using-the-estimated-regression-equation-for-estimation-and-prediction" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Using the Estimated Regression Equation for Estimation and Prediction</h1>
<section id="using-the-estimated-regression-equation-for-estimation-and-prediction-1" class="level2">
<h2 class="anchored" data-anchor-id="using-the-estimated-regression-equation-for-estimation-and-prediction-1">Using the Estimated Regression Equation for Estimation and Prediction</h2>
<div class="nonincremental">
<ul>
<li><p>A <strong>confidence interval</strong> is an interval estimate of the <strong>mean of all</strong> values of <span class="math inline">\(y\)</span> for a given value of <span class="math inline">\(x\)</span>.</p></li>
<li><p>A <strong>prediction interval</strong> is used whenever we want to <strong>predict an individual</strong> value of <span class="math inline">\(y\)</span> for a new randomly-chosen observation corresponding to a given value of <span class="math inline">\(x\)</span>.</p></li>
<li><p>The given <span class="math inline">\(x\)</span>-value is denoted by <span class="math inline">\(x^*\)</span> , and the corresponding point estimate is obtained from the estimated regression equation:</p></li>
</ul>
<p><span class="math display">\[
\hat{y}^* = b_0 + b_1 x^*
\]</span></p>
<ul>
<li>The margin of error (MOE) is larger for a prediction interval.</li>
</ul>
</div>
</section>
<section id="using-the-estimated-regression-equation-for-estimation-and-prediction-2" class="level2">
<h2 class="anchored" data-anchor-id="using-the-estimated-regression-equation-for-estimation-and-prediction-2">Using the Estimated Regression Equation for Estimation and Prediction</h2>
<div class="nonincremental">
<ul>
<li><strong>Confidence Interval Estimate of the mean</strong>, <span class="math inline">\(E(\hat{y}^*)\)</span>:</li>
</ul>
<p><span class="math display">\[
\hat{y}^* \pm t_{\alpha/2, n-2} s_{\hat{y}^*}
\]</span></p>
<ul>
<li><strong>Prediction Interval Estimate of individual</strong> <span class="math inline">\(\hat{y}^*\)</span>:</li>
</ul>
<p><span class="math display">\[
\hat{y}^* \pm t_{\alpha/2, n-2} s_{pred}
\]</span></p>
<p>where:</p>
<ul>
<li><strong>confidence coefficient</strong> is <span class="math inline">\(1-\alpha\)</span> and <span class="math inline">\(t_{\alpha/2, n-2}\)</span> is based on a <em>t</em> distribution with <span class="math inline">\(n-2\)</span> degrees of freedom.</li>
</ul>
</div>
</section>
<section id="point-estimation" class="level2">
<h2 class="anchored" data-anchor-id="point-estimation">Point Estimation</h2>
<div class="nonincremental">
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<p>To predict quarterly sales or expected quarterly sales of restaurants near a campus or campuses with 10,000 students (<span class="math inline">\(x* = 10\)</span>),</p>
<p><span class="math display">\[
\hat{y}^* = 60 + 5(10) = 110
\]</span></p>
<p>Predicted quarterly sales of $110,000</p>
</div>
</section>
<section id="sums-of-squares" class="level2">
<h2 class="anchored" data-anchor-id="sums-of-squares">Sums of Squares</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(i\)</span></th>
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(y_i\)</span></th>
<th><span class="math inline">\(x_i - \bar{x}\)</span></th>
<th><span class="math inline">\(y_i - \bar{y}\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})(y_i - \bar{y})\)</span></th>
<th><span class="math inline">\((x_i - \bar{x})^2\)</span></th>
<th><span class="math inline">\((y_i - \bar{y})^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2</td>
<td>58</td>
<td>-12</td>
<td>-72</td>
<td>864</td>
<td>144</td>
<td>5184</td>
</tr>
<tr class="even">
<td>2</td>
<td>6</td>
<td>105</td>
<td>-8</td>
<td>-25</td>
<td>200</td>
<td>64</td>
<td>625</td>
</tr>
<tr class="odd">
<td>3</td>
<td>8</td>
<td>88</td>
<td>-6</td>
<td>-42</td>
<td>252</td>
<td>36</td>
<td>1764</td>
</tr>
<tr class="even">
<td>4</td>
<td>8</td>
<td>118</td>
<td>-6</td>
<td>-12</td>
<td>72</td>
<td>36</td>
<td>144</td>
</tr>
<tr class="odd">
<td>5</td>
<td>12</td>
<td>117</td>
<td>-2</td>
<td>-13</td>
<td>26</td>
<td>4</td>
<td>169</td>
</tr>
<tr class="even">
<td>6</td>
<td>16</td>
<td>137</td>
<td>2</td>
<td>7</td>
<td>14</td>
<td>4</td>
<td>49</td>
</tr>
<tr class="odd">
<td>7</td>
<td>20</td>
<td>157</td>
<td>6</td>
<td>27</td>
<td>162</td>
<td>36</td>
<td>729</td>
</tr>
<tr class="even">
<td>8</td>
<td>20</td>
<td>169</td>
<td>6</td>
<td>39</td>
<td>234</td>
<td>36</td>
<td>1521</td>
</tr>
<tr class="odd">
<td>9</td>
<td>22</td>
<td>149</td>
<td>8</td>
<td>19</td>
<td>152</td>
<td>64</td>
<td>361</td>
</tr>
<tr class="even">
<td>10</td>
<td>26</td>
<td>202</td>
<td>12</td>
<td>72</td>
<td>864</td>
<td>144</td>
<td>5184</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td>140</td>
<td>1300</td>
<td></td>
<td></td>
<td>2840</td>
<td>568</td>
<td>15730</td>
</tr>
</tbody>
</table>
<center>
<span class="math inline">\(\bar{x} = 14, \bar{y} = 130\)</span>
</center>
<p><br></p>
</section>
<section id="confidence-interval-for-ehaty" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-ehaty">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></h2>
<div class="nonincremental">
<p>Estimate of the Standard Deviation of <span class="math inline">\(\hat{y}^*\)</span>:</p>
<p><span class="math display">\[
s_{\hat{y}^*} = s \sqrt{\frac{1}{n} + \frac{(x^* - \bar{x})^2}{\sum (x_i - \bar{x})^2}}
\]</span></p>
<p><span class="math display">\[
= 13.829 \sqrt{\frac{1}{10} + \frac{(10 - 14)^2}{568}}
\]</span></p>
<p><span class="math display">\[
= 13.829 \sqrt{.1282} = 4.95
\]</span></p>
</div>
</section>
<section id="confidence-interval-for-ehaty-1" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-ehaty-1">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></h2>
<p>95% confidence interval of the <strong>mean</strong> quarterly sales for all Armand’s restaurants located near campuses with 10,000 students is</p>
<p><span class="math display">\[
\hat{y}^* \pm t_{\alpha/2} s_{\hat{y}^*}
\]</span></p>
<p><span class="math display">\[
110 \pm 2.306(4.95)
\]</span></p>
<p><span class="math display">\[
110 \pm 11.415, \text{ or } \$98,585 \text{ to } \$121,415
\]</span></p>
<p>We are 95% confident that the <strong>mean</strong> quarterly sales for <strong>all</strong> Armand’s restaurants located near campuses with 10,000 students falls between $98,585 and $121,415.</p>
</section>
<section id="confidence-interval-for-ehaty-2" class="level2">
<h2 class="anchored" data-anchor-id="confidence-interval-for-ehaty-2">Confidence Interval for <span class="math inline">\(E(\hat{y}^*)\)</span></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_confidence_interval_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:99.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prediction-interval-for-y" class="level2">
<h2 class="anchored" data-anchor-id="prediction-interval-for-y">Prediction Interval for <span class="math inline">\(y^*\)</span></h2>
<div class="nonincremental">
<p>Estimate of the Standard Deviation of an <strong>Individual Value</strong> of <span class="math inline">\(y^*\)</span></p>
<p><span class="math display">\[
s_{pred} = s \sqrt{1 + \frac{1}{n} + \frac{(x^* - \bar{x})^2}{\sum (x_i - \bar{x})^2}}
\]</span></p>
<p><span class="math display">\[
s_{pred} = 13.829 \sqrt{1 + \frac{1}{10} + \frac{(10 - 14)^2}{568}}
\]</span></p>
<p><span class="math display">\[
= 13.829 \sqrt{1.282} = 14.69
\]</span></p>
</div>
</section>
<section id="prediction-interval-for-y-1" class="level2">
<h2 class="anchored" data-anchor-id="prediction-interval-for-y-1">Prediction Interval for <span class="math inline">\(y^*\)</span></h2>
<div class="nonincremental">
<p>95% prediction interval for quarterly sales for the new Armand’s restaurant located near a campus with 10,000 students is</p>
<p><span class="math display">\[
\hat{y}^* \pm t_{\alpha/2} s_{pred}
\]</span></p>
<p><span class="math display">\[
110 \pm 2.306(14.69)
\]</span></p>
<p><span class="math display">\[
110 \pm 33.875, \text{ or } \$76,125 \text{ to } \$143,875
\]</span></p>
<p>If we randomly select <strong>one</strong> Armand’s restaurant located near a campus with 10,000 students, we are 95% confident that its quarterly sales will be between $76,125 and $143,875.</p>
</div>
</section>
<section id="prediction-interval-for-y-2" class="level2">
<h2 class="anchored" data-anchor-id="prediction-interval-for-y-2">Prediction Interval for <span class="math inline">\(y^*\)</span></h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_pred_interval_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:99.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="comments" class="level2">
<h2 class="anchored" data-anchor-id="comments">Comments</h2>
<p><br></p>
<div class="nonincremental">
<ul>
<li><p>Prediction intervals for individuals are wider than the corresponding confidence intervals for means.</p></li>
<li><p>Two <span class="math inline">\(x\)</span>-values with the same distance to the <span class="math inline">\(\bar{x}\)</span>, their corresponding confidence intervals have the same width (and hence, the same margin of error). True also for the prediction intervals.</p></li>
<li><p>The confidence interval is wider when the given <span class="math inline">\(x\)</span> is further away from the <span class="math inline">\(\bar{x}\)</span> – It is more difficult to predict for outlying <span class="math inline">\(x\)</span>’s.</p></li>
</ul>
</div>
</section>
</section>
<section id="residual-analysis-validating-model-assumptions" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Residual Analysis: Validating Model Assumptions</h1>
<section id="residual-analysis-validating-model-assumptions-1" class="level2">
<h2 class="anchored" data-anchor-id="residual-analysis-validating-model-assumptions-1">Residual Analysis: Validating Model Assumptions</h2>
<div class="nonincremental">
<ul>
<li><p>If the assumptions about the error term <span class="math inline">\(\epsilon\)</span> appear questionable, the hypothesis tests about the significance of the regression relationship and the interval estimation results may not be valid.</p></li>
<li><p>The residuals provide the best information about <span class="math inline">\(\epsilon\)</span>.</p></li>
<li><p>Residual for observation <span class="math inline">\(i\)</span></p></li>
</ul>
<p><span class="math display">\[
y_i - \hat{y}_i
\]</span></p>
<ul>
<li>Much of the residual analysis is based on an examination of graphical plots.</li>
</ul>
</div>
</section>
<section id="model-assumptions-and-validation-procedures-with-diagnosis-plots" class="level2">
<h2 class="anchored" data-anchor-id="model-assumptions-and-validation-procedures-with-diagnosis-plots">Model Assumptions and Validation Procedures with Diagnosis Plots</h2>
<ol type="1">
<li><p><span class="math inline">\(E(\epsilon) = 0\)</span>.</p>
<ul>
<li><strong>Validation procedure:</strong> A plot of residuals against the predicted values of the dependent variable <span class="math inline">\(y\)</span>.</li>
</ul></li>
<li><p>The variance of <span class="math inline">\(\epsilon\)</span>, denoted by <span class="math inline">\(\sigma^2\)</span>, is the same for all values of <span class="math inline">\(x\)</span>.</p>
<ul>
<li><strong>Validation procedure:</strong> A plot of the residuals against values of the independent variable <span class="math inline">\(x\)</span>.</li>
</ul></li>
<li><p>The values of <span class="math inline">\(\epsilon\)</span> are independent.</p>
<ul>
<li><strong>Validation procedure:</strong> A standardized residual plot.</li>
</ul></li>
<li><p>The error term <span class="math inline">\(\epsilon\)</span> has a normal distribution.</p>
<ul>
<li><strong>Validation procedure:</strong> A normal probability plot.</li>
</ul></li>
</ol>
</section>
<section id="residual-plot-against-x" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-against-x">Residual Plot Against <span class="math inline">\(x\)</span></h2>
<div style="font-size: 80%;">
<p>If the assumption that the variance of <span class="math inline">\(\epsilon\)</span> is the same (constant) for all values of <span class="math inline">\(x\)</span> is valid, and the assumed regression model is an adequate representation of the relationship between the variables, then the residual plot should give an overall impression of a horizontal band of points.</p>
</div>
<div class="columns">
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_residual_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:99.0%"></p>
</figure>
</div>
</div>
</div>
<center>
Panel A
</center>
</div>
</div>
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_residual_02.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:99.0%"></p>
</figure>
</div>
</div>
</div>
<center>
Panel B
</center>
</div>
</div>
<div class="column quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/reg_residual_03.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:99.0%"></p>
</figure>
</div>
</div>
</div>
<center>
Panel C
</center>
</div>
</div>
</div>
</div>
</div>
<p><br></p>
</section>
<section id="residual-plot-against-x-1" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-against-x-1">Residual Plot Against <span class="math inline">\(x\)</span></h2>
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 22%">
<col style="width: 30%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Student Population (<span class="math inline">\(x_i\)</span>)</th>
<th>Sales (<span class="math inline">\(y_i\)</span>)</th>
<th>Predicted sales <span class="math inline">\(y_i = 60 + 5(x_i)\)</span></th>
<th>Residuals (<span class="math inline">\(y_i - \hat{y_i}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>58</td>
<td>70</td>
<td>-12</td>
</tr>
<tr class="even">
<td>6</td>
<td>105</td>
<td>90</td>
<td>15</td>
</tr>
<tr class="odd">
<td>8</td>
<td>88</td>
<td>100</td>
<td>-12</td>
</tr>
<tr class="even">
<td>8</td>
<td>118</td>
<td>100</td>
<td>18</td>
</tr>
<tr class="odd">
<td>12</td>
<td>117</td>
<td>120</td>
<td>-3</td>
</tr>
<tr class="even">
<td>16</td>
<td>137</td>
<td>140</td>
<td>-3</td>
</tr>
<tr class="odd">
<td>20</td>
<td>157</td>
<td>160</td>
<td>-3</td>
</tr>
<tr class="even">
<td>20</td>
<td>169</td>
<td>160</td>
<td>9</td>
</tr>
<tr class="odd">
<td>22</td>
<td>149</td>
<td>170</td>
<td>-21</td>
</tr>
<tr class="even">
<td>26</td>
<td>202</td>
<td>190</td>
<td>12</td>
</tr>
</tbody>
</table>
</section>
<section id="residual-plot-against-x-2" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-against-x-2">Residual Plot Against <span class="math inline">\(x\)</span></h2>
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<p>Plot of the residuals against the independent variable <span class="math inline">\(x\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_residual_x.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div style="font-size: 80%;">
<ul>
<li>The residuals appear to approximate the horizontal pattern in Panel A.</li>
<li>Based on this subjective evaluation, we conclude that the residual plot does not provide evidence that the assumptions made for Armand’s regression model should be challenged.</li>
<li>We can be confident that Armand’s simple regression model is valid.</li>
</ul>
</div>
</section>
<section id="residual-plot-against-x---excel" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-against-x---excel">Residual Plot Against <span class="math inline">\(x\)</span> - Excel</h2>
<div class="nonincremental">
<div class="columns">
<div class="column" style="text-align: center; justify-content: center; align-items: center;">
<ul>
<li><p>Using Excel to Produce a Residual Plot</p>
<ul>
<li><p>The steps outlined earlier to obtain the regression output are performed with one change.</p></li>
<li><p>When the Regression dialog box appears, we must also select the <strong>Residual Plot</strong> option.</p></li>
<li><p>The output will include two new items:</p>
<ul>
<li>A plot of the residuals against the independent variable, and</li>
<li>A list of predicted values of <span class="math inline">\(y\)</span> and the corresponding residual values.</li>
</ul></li>
</ul></li>
</ul>
</div><div class="column" style="text-align: center; justify-content: center; align-items: center;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_residual_excel.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="residual-plot-against-haty" class="level2">
<h2 class="anchored" data-anchor-id="residual-plot-against-haty">Residual Plot Against <span class="math inline">\(\hat{y}\)</span></h2>
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<p>Plot of the residuals against the independent variable <span class="math inline">\(\hat{y}\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_residual_y.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<div style="font-size: 80%;">
<ul>
<li>The pattern of this residual plot is the same as the pattern of the residual plot against the independent variable <span class="math inline">\(x\)</span>.</li>
<li>It is not a pattern that would lead us to question the model assumptions.</li>
<li>For simple linear regression, both the residual plot against <span class="math inline">\(x\)</span> and the residual plot against <span class="math inline">\(\hat{y}\)</span> provide the same pattern.</li>
<li>For multiple regression analysis, the residual plot against <span class="math inline">\(\hat{y}\)</span> is more widely used because of the presence of more than one independent variable.</li>
</ul>
</div>
</section>
<section id="standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residuals">Standardized Residuals</h2>
<div class="nonincremental">
<ul>
<li>Standardized Residual for Observation <span class="math inline">\(i\)</span></li>
</ul>
<p><span class="math display">\[
\frac{y_i - \hat{y_i}}{s_{y_i - \hat{y_i}}}
\]</span></p>
<p>where <span class="math inline">\(s_{y_i - \hat{y_i}}\)</span> is the standard deviation of residual <span class="math inline">\(i\)</span></p>
<p><span class="math display">\[
s_{y_i - \hat{y_i}} = s \sqrt{1 + h_i}
\]</span> where <span class="math inline">\(s\)</span> is the standard error of the estimate</p>
<p><span class="math display">\[
h_i = \frac{1}{n} + \frac{(x_i - \bar{x})^2}{\sum (x_i - \bar{x})^2}
\]</span></p>
</div>
</section>
<section id="standardized-residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residual-plot">Standardized Residual Plot</h2>
<ul>
<li><p>The standardized residual plot can provide insight about the assumption that the error term <span class="math inline">\(\epsilon\)</span> has a normal distribution.</p></li>
<li><p>If this assumption is satisfied, the distribution of the standardized residuals should appear to come from a standard normal probability distribution.</p>
<ul>
<li>Empirical rule applies.</li>
</ul></li>
</ul>
</section>
<section id="standardized-residual" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residual">Standardized Residual</h2>
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 30%">
<col style="width: 26%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Observation</th>
<th>Predicted sales <span class="math inline">\(y_i = 60 + 5(x_i)\)</span></th>
<th>Residuals (<span class="math inline">\(y_i - \hat{y_i}\)</span>)</th>
<th>Standardized Residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>70</td>
<td>-12</td>
<td>-1.0792</td>
</tr>
<tr class="even">
<td>2</td>
<td>90</td>
<td>15</td>
<td>1.2224</td>
</tr>
<tr class="odd">
<td>3</td>
<td>100</td>
<td>-12</td>
<td>-.9487</td>
</tr>
<tr class="even">
<td>4</td>
<td>100</td>
<td>18</td>
<td>1.4230</td>
</tr>
<tr class="odd">
<td>5</td>
<td>120</td>
<td>-3</td>
<td>-.2296</td>
</tr>
<tr class="even">
<td>6</td>
<td>140</td>
<td>-3</td>
<td>-.2296</td>
</tr>
<tr class="odd">
<td>7</td>
<td>160</td>
<td>-3</td>
<td>-.2372</td>
</tr>
<tr class="even">
<td>8</td>
<td>160</td>
<td>9</td>
<td>.7115</td>
</tr>
<tr class="odd">
<td>9</td>
<td>170</td>
<td>-21</td>
<td>-1.7114</td>
</tr>
<tr class="even">
<td>10</td>
<td>190</td>
<td>12</td>
<td>1.0792</td>
</tr>
</tbody>
</table>
</section>
<section id="standardized-residual-plot-1" class="level2">
<h2 class="anchored" data-anchor-id="standardized-residual-plot-1">Standardized Residual Plot</h2>
<p><strong>Example:</strong> Armand’s Pizza Parlors</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_residual_std.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>All of the standardized residuals are between -2 and +2 indicating that there is no reason to question the assumption that ε has a normal distribution.</li>
</ul>
</section>
<section id="using-excel-to-construct-a-standardized-residual-plot" class="level2">
<h2 class="anchored" data-anchor-id="using-excel-to-construct-a-standardized-residual-plot">Using Excel to construct a Standardized Residual Plot</h2>
<p><strong>Example: Armand’s Pizza Parlors</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_plot_residual_std_excel.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="normal-probability-plot" class="level2">
<h2 class="anchored" data-anchor-id="normal-probability-plot">Normal Probability Plot</h2>
<p>Another approach for determining the validity of the assumption that the error term has a normal distribution.</p>
<p>To show how a normal probability plot is developed, we introduce the concept of <strong>normal scores</strong>:</p>
<blockquote class="blockquote">
<p>Suppose 10 values are selected randomly from a normal probability distribution with a mean of zero and a standard deviation of one, and that the sampling process is repeated over and over with the values in each sample of 10 ordered from smallest to largest. For now, let us consider only the smallest value in each sample. The random variable representing the smallest value obtained in repeated sampling is called the <strong>first-order statistic</strong>.</p>
</blockquote>
<blockquote class="blockquote">
<p>For samples of size 10 from a standard normal probability distribution, the expected value of the first-order statistic is -1.55. This expected value is called a <strong>normal score</strong>. For the case with a sample of size <span class="math inline">\(n = 10\)</span>, there are 10 order statistics and 10 normal scores (next slide). In general, a data set consisting of <span class="math inline">\(n\)</span> observations will have <span class="math inline">\(n\)</span> order statistics and hence <span class="math inline">\(n\)</span> normal scores.</p>
</blockquote>
<p><strong>Normal Scores</strong>: are expected values of the order statistics from a standard normal distribution.</p>
</section>
<section id="normal-probability-plot-1" class="level2">
<h2 class="anchored" data-anchor-id="normal-probability-plot-1">Normal Probability Plot</h2>
<p><strong>Normal Scores for</strong> <span class="math inline">\(n = 10\)</span></p>
<center>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Order Statistic</th>
<th>Normal Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>-1.55</td>
</tr>
<tr class="even">
<td>2</td>
<td>-1.00</td>
</tr>
<tr class="odd">
<td>3</td>
<td>-0.65</td>
</tr>
<tr class="even">
<td>4</td>
<td>-0.37</td>
</tr>
<tr class="odd">
<td>5</td>
<td>-0.12</td>
</tr>
<tr class="even">
<td>6</td>
<td>0.12</td>
</tr>
<tr class="odd">
<td>7</td>
<td>0.37</td>
</tr>
<tr class="even">
<td>8</td>
<td>0.65</td>
</tr>
<tr class="odd">
<td>9</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>10</td>
<td>1.55</td>
</tr>
</tbody>
</table>
</center>
</section>
<section id="normal-probability-plot-2" class="level2">
<h2 class="anchored" data-anchor-id="normal-probability-plot-2">Normal Probability Plot</h2>
<div style="font-size: 80%;">
<p>To determine whether the standardized residuals for Armand’s Pizza Parlors appear to come from a standard normal probability distribution.</p>
<p>We order the 10 standardized residuals in parallel with the 10 normal scores:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Normal Scores</th>
<th>Ordered Standardized Residuals</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>-1.55</td>
<td>-1.7114</td>
</tr>
<tr class="even">
<td>-1.00</td>
<td>-1.0792</td>
</tr>
<tr class="odd">
<td>-0.65</td>
<td>-0.9487</td>
</tr>
<tr class="even">
<td>-0.37</td>
<td>-0.2372</td>
</tr>
<tr class="odd">
<td>-0.12</td>
<td>-0.2296</td>
</tr>
<tr class="even">
<td>0.12</td>
<td>-0.2296</td>
</tr>
<tr class="odd">
<td>0.37</td>
<td>0.7115</td>
</tr>
<tr class="even">
<td>0.65</td>
<td>1.0792</td>
</tr>
<tr class="odd">
<td>1.00</td>
<td>1.2224</td>
</tr>
<tr class="even">
<td>1.55</td>
<td>1.4230</td>
</tr>
</tbody>
</table>
<p><strong>Interpreting the Normal Probability Plot</strong>: If the normality assumption is satisfied, the smallest standardized residual should be close to the smallest normal score, the next smallest standardized residual should be close to the next smallest normal score, and so on.</p>
</div>
</section>
<section id="normal-probability-plot-3" class="level2">
<h2 class="anchored" data-anchor-id="normal-probability-plot-3">Normal Probability Plot</h2>
<div style="font-size: 70%;">
<p>A plot with the normal scores on the horizontal axis and the corresponding standardized residuals on the vertical axis, the plotted points should cluster closely around a 45-degree line passing through the origin if the standardized residuals are approximately normally distributed.</p>
<div class="fragment">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/armands_pizza_normality_plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The points are grouped closely about the line. Therefore, we can conclude that the assumption of the error term having a normal probability distribution is reasonable.</li>
<li>In general, the more closely the points are clustered about the 45-degree line, the stronger the evidence supporting the normality assumption. Any substantial curvature in the normal probability plot is evidence that the residuals have not come from a normal distribution.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="outliers-and-influential-observations" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Outliers and Influential Observations</h1>
<section id="outliers" class="level2">
<h2 class="anchored" data-anchor-id="outliers">Outliers</h2>
<p>An <strong>outlier</strong> is a data point (observation) that does not fit the trend shown by the remaining data. Represent observations that are suspect and warrant careful examination.</p>
<ul>
<li><p><strong>Erroneous Data</strong></p>
<ul>
<li><p>Investigate the source of the outlier to identify any errors in data collection or entry.</p></li>
<li><p>Correct the data point if possible, or remove it if the correct value cannot be determined.</p></li>
</ul></li>
<li><p><strong>Violation of Model Assumptions</strong></p>
<ul>
<li><p>Use diagnostic tools to check if the outlier violates the assumptions of simple regression.</p></li>
<li><p>Consider alternative models, such as transformations or robust regression methods, if the assumptions are violated.</p></li>
</ul></li>
<li><p><strong>Legitimate but Unusual Observations</strong></p>
<ul>
<li><p>Recognize that some outliers are natural occurrences and represent rare events.</p></li>
<li><p>Retain these outliers in the analysis to reflect the true variability in the data.</p></li>
<li><p>Report and interpret the presence of these outliers in the context of the study.</p></li>
</ul></li>
</ul>
</section>
<section id="detecting-outliers" class="level2">
<h2 class="anchored" data-anchor-id="detecting-outliers">Detecting Outliers</h2>
<div style="font-size: 80%;">
<p>For the case of simple linear regression, one can often detect outliers by simply examining the scatter diagram.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/outlier_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<center>
<span class="math inline">\(R^2 = .4968\)</span>
</center>
<p>Given the pattern of the rest of the data, we would have expected <span class="math inline">\(y_4\)</span> to be much smaller and hence would consider observation 4 to be an outlier.</p>
</div>
</section>
<section id="detecting-outliers-with-standardized-residuals" class="level2">
<h2 class="anchored" data-anchor-id="detecting-outliers-with-standardized-residuals">Detecting Outliers with Standardized Residuals</h2>
<div style="font-size: 70%;">
<p>If an observation deviates greatly from the pattern of the rest of the data, the corresponding standardized residual will be large in absolute value.</p>
<p>Any observation with a standardized residual of less than -2 or greater than +2 is a potential outlier. With normally distributed errors, standardized residuals should be outside these limits approximately 5% of the time.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/outlier_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the residual output section in the Figure we see that the standard residual value for observation 4 is 2.68.</p>
</div>
</section>
<section id="detecting-outliers-1" class="level2">
<h2 class="anchored" data-anchor-id="detecting-outliers-1">Detecting Outliers</h2>
<div style="font-size: 80%;">
<p>The identification of the outlier enables us to correct the data error and improve the regression results. This is the result with <span class="math inline">\(y_4 = 30\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/outlier_02.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Now, no standard residuals are less than -2 or greater than +2.</li>
<li>The value of <span class="math inline">\(R^2\)</span> has increased from 0.4968 to 0.8380</li>
<li>The value of <span class="math inline">\(b_0\)</span> has decreased from 64.95 to 59.23.</li>
<li>The slope of the line has changed from -7.330 to -6.949.</li>
</ul>
</div>
</section>
<section id="influential-observations" class="level2">
<h2 class="anchored" data-anchor-id="influential-observations">Influential Observations</h2>
<p><br></p>
<ul>
<li><p>An <strong>influential observation</strong> is an observation that has a strong influence on the regression results.</p></li>
<li><p>An influential observation may be an outlier, it may correspond to an <span class="math inline">\(x\)</span> value far from its mean, or it may be caused by a combination of a somewhat off-trend <span class="math inline">\(y\)</span> value and a somewhat extreme <span class="math inline">\(x\)</span> value.</p></li>
<li><p>If the observation is valid, it can contribute to a better understanding of the appropriate model and can lead to a better estimated regression equation.</p></li>
</ul>
</section>
<section id="detecting-influential-observations" class="level2">
<h2 class="anchored" data-anchor-id="detecting-influential-observations">Detecting Influential Observations</h2>
<div style="font-size: 80%;">
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figs/influential_01.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:40.0%"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<p>With observation 7 deleted,</p>
<ul>
<li><p>The value of <span class="math inline">\(b_0\)</span> has increased from 127.4 to 138.1.</p></li>
<li><p>The slope of the line has changed from -0.425 to -1.090.</p></li>
</ul>
</div>
</section>
<section id="detecting-influential-observations-1" class="level2">
<h2 class="anchored" data-anchor-id="detecting-influential-observations-1">Detecting Influential Observations</h2>
<p><strong>High Leverage Points:</strong> Observations with extreme values for the independent variable. Observation 7 in the data set shown is a point with high leverage.</p>
<p>The leverage of an observation is determined by how far the value of the independent variable is from its mean value.</p>
<p>For the single-independent-variable case, the leverage of the <span class="math inline">\(i\)</span>th observation, denoted <span class="math inline">\(h_i\)</span>, can be computed using:</p>
<p><span class="math display">\[
h_i = \frac{1}{n} + \frac{(x_i - \bar{x})^2}{\sum (x_i - \bar{x})^2}
\]</span></p>
<p>From the formula, farther <span class="math inline">\(x_i\)</span> is from its mean <span class="math inline">\(\bar{x}\)</span>, the higher the leverage of observation <span class="math inline">\(i\)</span>.</p>
</section>
<section id="detecting-influential-observations-2" class="level2">
<h2 class="anchored" data-anchor-id="detecting-influential-observations-2">Detecting Influential Observations</h2>
<div style="font-size: 70%;">
<p>For the data shown, the leverage of observation 7 is as follows:</p>
<p><span class="math display">\[
h_i = \frac{1}{n} + \frac{(x_i - \bar{x})^2}{\sum (x_i - \bar{x})^2} = \frac{1}{7} + \frac{(70 - 24.286)^2}{2621.43} = 0.94
\]</span></p>
<p>For simple linear regression, we consider observations as having high leverage if <span class="math inline">\(h_i &gt; \frac{6}{n}\)</span>. For the example, <span class="math inline">\(\frac{6}{n} = \frac{6}{7} = 0.86\)</span>.</p>
<p>Thus, because <span class="math inline">\(h_i = 0.94 &gt; 0.86\)</span>, observation 7 would be identified as having high leverage.</p>
<p><br></p>
<div class="fragment">
<p><strong>Notes and Comments</strong>:</p>
<ul>
<li><p>The number <strong>6</strong> in the criterion <span class="math inline">\(h_i &gt; \frac{6}{n}\)</span> is an arbitrary rule of thumb used to identify high leverage points in linear regression. Some statisticians use <span class="math inline">\(\frac{2p}{n}\)</span>, where <span class="math inline">\(p\)</span> is the number of predictors plus one (for the intercept) in the model.</p></li>
<li><p>Once an observation is identified as potentially influential because of a large residual or high leverage, its impact on the estimated regression equation should be evaluated.</p></li>
<li><p>More advanced texts discuss diagnostics for doing so. However, if one is not familiar with the more advanced material, a simple procedure is to run the regression analysis with and without the observation. This approach will reveal the influence of the observation on the results.</p></li>
</ul>
</div>
</div>
</section>
</section>
<section id="summary" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Summary</h1>
<section id="summary-1" class="level2">
<h2 class="anchored" data-anchor-id="summary-1">Summary</h2>
<div class="nonincremental">
<p>Some key takeaways from this session:</p>
<ul>
<li><p><strong>Simple Linear Regression Model</strong>: Helps to understand the linear relationship between two variables—predicting the Dependent Variable (<span class="math inline">\(Y\)</span>) based on the Independent Variable (<span class="math inline">\(X\)</span>).</p>
<ul>
<li>This method is foundational for exploring how variables are related and how changes in one variable can predict changes in another.</li>
</ul></li>
<li><p><strong>Model Interpretation and Assumptions</strong>: It is essential to interpret the regression coefficients and validate model assumptions to ensure that the model is reliable.</p>
<ul>
<li>Assumptions include linearity, independence, homoscedasticity (constant variance), and normality of residuals.</li>
</ul></li>
<li><p><strong>Residual Analysis</strong>: Residual plots and other diagnostic tools are critical for validating the assumptions of the regression model and ensuring its accuracy.</p>
<ul>
<li>Proper validation techniques prevent misinterpretation of data and help maintain the integrity of the analysis.</li>
</ul></li>
</ul>
</div>
</section>
</section>
<section id="thank-you" class="level1" data-background-color="#cfb991">
<h1 data-background-color="#cfb991">Thank you!</h1>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>